import React from 'react';
import {ArrowUpRight,ArrowRight,CalendarDays,Check,ChevronRight,GitBranch,Sparkles,Plus} from 'lucide-react';
import {categories,dayNumber,dayKey} from './data';
import {Intro,ArticleCard,ActivityHeatmap,OrbitArt} from './ui';
export default function Dashboard({articles,state,today,question,questionId,onChallenge,onNewThesis,go,onOpen,onBookmark,onCategory}){
 const concepts=articles.filter(a=>a.type!=='case'),cases=articles.filter(a=>a.type==='case');
 const unread=concepts.filter(a=>!state.completed.includes(a.id)),pool=unread.length?unread:concepts;
 const curated=['loss-aversion','base-rates','margin-of-safety'].map(id=>pool.find(a=>a.id===id)).filter(Boolean);
 const recommended=[...curated,...pool.filter(a=>!curated.some(c=>c.id===a.id))].slice(0,3);
 const todayActivity=state.activity.filter(a=>(a.day||(a.date?dayKey(new Date(a.date)):null))===today);
 const done=[!!state.answers[questionId],todayActivity.some(a=>a.type==='learn'),state.theses.some(t=>dayKey(new Date(t.createdAt))===today)];
 const days=new Set(state.activity.map(a=>a.day||(a.date?dayKey(new Date(a.date)):null)).filter(Boolean));
 const currentCase=cases[dayNumber(today)%Math.max(cases.length,1)];
 return <><Intro eyebrow="THINK DEEPER. SEE FURTHER." title="理解世界，从一个好问题开始" description="跳出信息的噪声，在知识之间建立连接，让判断更进一步。"><div className="intro-date"><CalendarDays size={16}/>{new Date(today+'T12:00:00').toLocaleDateString('zh-CN',{month:'long',day:'numeric',weekday:'long'})}</div></Intro>
 <div className="dashboard-layout"><div className="dashboard-main">
 <section className="challenge-hero"><div className="hero-copy"><div className="pill hero-pill"><span/>今日认知挑战<i/>约 5 分钟</div><h2>{question.title}</h2><p>{question.context}</p><div className="hero-tags">{question.tags.map(t=><span key={t}>{t}</span>)}</div><button className="button primary" onClick={onChallenge}>{state.answers[questionId]?'回看我的思考':'开始思考'}<ArrowUpRight size={17}/></button><div className="hero-bottom">先形成自己的判断，再看另一种视角。</div></div><OrbitArt onCategory={onCategory}/><div className="hero-coordinate">CONNECTED THINKING / 06 PERSPECTIVES</div></section>
 <section className="perspectives-section"><div className="section-header"><h2>连接六种视角<span>从底层逻辑，到投资判断</span></h2><button className="text-button" onClick={()=>go('graph')}>认知图谱<ArrowUpRight size={16}/></button></div><div className="perspective-grid">{categories.map(c=><button key={c.id} className="perspective-card" onClick={()=>onCategory(c.id)}><span className="category-icon" style={{color:c.color,background:c.color+'13'}}><c.icon size={21}/></span><strong>{c.label}</strong><small>{concepts.filter(a=>a.category===c.id).length} 个核心概念</small><ArrowUpRight className="category-arrow" size={14}/></button>)}</div></section>
 <section><div className="section-header"><h2>值得深入的三个概念<span>建立你的思维工具箱</span></h2><button className="text-button" onClick={()=>onCategory('all')}>探索全部<ArrowRight size={16}/></button></div><div className="article-grid dashboard-articles">{recommended.map(a=><ArticleCard key={a.id} article={a} state={state} onOpen={onOpen} onBookmark={onBookmark}/>)}</div></section>
 {currentCase&&<section className="case-feature"><div className="case-visual"><span>CASE STUDY</span><div className="case-bars">{[27,36,43,59,73,92,54,35,43,57].map((v,i)=><i key={i} style={{height:v+'%',opacity:.35+i*.06}}/>)}</div><span>历史不会重复，机制可以辨认。</span></div><div className="case-copy"><div className="eyebrow">把概念放回真实世界</div><h3>{currentCase.title}</h3><p>{currentCase.summary}</p><button className="text-button" onClick={()=>onOpen(currentCase.id)}>拆解这个案例<ArrowRight size={16}/></button></div></section>}
 </div><aside className="dashboard-rail">
 <section className="path-card"><div className="section-header"><h2>今天的学习路径</h2><span className="small-badge">15 MIN</span></div><p className="muted rail-subtitle">少一点浏览，多一点理解。</p><div className="path-steps">{[{title:'提出一个好问题',subtitle:'用自己的语言，写下第一判断',action:onChallenge},{title:'理解一个底层概念',subtitle:recommended[0]?.title||'从知识探索开始',action:()=>recommended[0]&&onOpen(recommended[0].id)},{title:'留下一条可检验的判断',subtitle:'记录概率，给未来一个参照',action:onNewThesis}].map((s,i)=><button key={s.title} className={'path-step '+(done[i]?'done':'')} onClick={s.action}><span className="step-index">{done[i]?<Check size={15}/>:'0'+(i+1)}</span><span className="step-copy"><strong>{s.title}</strong><small>{s.subtitle}</small></span><ChevronRight size={15}/></button>)}</div><div className="daily-progress"><div><span>今日完成</span><strong>{done.filter(Boolean).length}<small> / 3</small></strong></div><div className="progress-track"><i style={{width:done.filter(Boolean).length/3*100+'%'}}/></div></div></section>
 <section className="growth-card"><div className="section-header"><h2>认知，在持续积累</h2><GitBranch size={17}/></div><div className="growth-stats"><div><strong>{state.completed.length}<small> / {articles.length}</small></strong><span>已理解的知识</span></div><div><strong>{days.size}<small> 天</small></strong><span>有记录的日子</span></div></div><ActivityHeatmap activity={state.activity}/><button className="text-button" onClick={()=>go('profile')}>查看学习档案<ArrowRight size={15}/></button></section>
 <section className="note-card"><div className="eyebrow"><Sparkles size={14}/>给思考留一点空间</div><blockquote>“我可能错在哪里？”<br/>是一个比“我为什么对”<br/>更有价值的问题。</blockquote><p>记录判断时，别忘了写下<br/>能让你改变主意的证据。</p><button className="text-button" onClick={onNewThesis}>写下我的判断<Plus size={15}/></button></section>
 </aside></div></>
}
