import React,{useState,useEffect,useRef,useCallback} from 'react';
import {Menu,Search,ChevronRight,Settings2,RefreshCw,CheckCircle2,BookOpen} from 'lucide-react';
import {categories,nav,questions,dayKey,dayNumber,emptyState} from './data';
import {Empty} from './ui';
import Dashboard from './Dashboard';
import {Library,ArticleReader,Graph,SearchModal} from './Knowledge';
import {Challenge,ThesisForm,ReviewForm,Theses} from './Training';
import Profile from './Profile';
import BackToTop from './BackToTop';
import {getInsightRoute,navigateInsight} from './router';
const getRoute=()=>{const raw=getInsightRoute();return raw.startsWith('article/')?{page:'article',id:raw.slice(8)}:{page:nav.some(n=>n.id===raw)?raw:'today'}};
async function request(url,options){const r=await fetch(url,options),data=await r.json();if(!r.ok)throw new Error(data.error||'请求失败（'+r.status+'）');return data}
export default function App(){
 const [articles,setArticles]=useState([]),[state,setState]=useState(emptyState),[loading,setLoading]=useState(true),[error,setError]=useState(''),[saveError,setSaveError]=useState(''),[saving,setSaving]=useState(false),[route,setRoute]=useState(getRoute),[searchOpen,setSearchOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[challengeOpen,setChallengeOpen]=useState(false),[editor,setEditor]=useState(null),[review,setReview]=useState(null),[toast,setToast]=useState(''),[category,setCategory]=useState('all'),[today,setToday]=useState(dayKey());
 const stateRef=useRef(emptyState),queue=useRef(Promise.resolve()),pending=useRef(0),timer=useRef(null),question=questions[dayNumber(today)%questions.length],questionId='daily-'+today;
 const notify=useCallback(message=>{setToast(message);clearTimeout(timer.current);timer.current=setTimeout(()=>setToast(''),3200)},[]);
 const load=useCallback(async()=>{setLoading(true);setError('');try{const [content,data]=await Promise.all([request('/insight/api/content'),request('/insight/api/state')]);setArticles(content.articles);stateRef.current={...emptyState,...data};setState(stateRef.current)}catch(e){setError('加载失败：'+e.message+'。请确认本地服务已启动。')}finally{setLoading(false)}},[]);
 useEffect(()=>{load();const t=setInterval(()=>setToday(dayKey()),30000);return()=>{clearInterval(t);clearTimeout(timer.current)}},[load]);
 useEffect(()=>{const hash=()=>{setRoute(getRoute());setMobileOpen(false);window.scrollTo({top:0,behavior:'instant'})},key=e=>{if((e.ctrlKey||e.metaKey)&&e.key==='k'){e.preventDefault();setSearchOpen(v=>!v)}};window.addEventListener('hashchange',hash);window.addEventListener('keydown',key);return()=>{window.removeEventListener('hashchange',hash);window.removeEventListener('keydown',key)}},[]);
 const persist=useCallback((updater,options={})=>{
   pending.current++;setSaving(true);
   const task=queue.current.catch(()=>{}).then(async()=>{try{const next=typeof updater==='function'?updater(stateRef.current):{...stateRef.current,...updater};const saved=await request('/insight/api/state',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify(next)});stateRef.current=saved;setState(saved);setSaveError('');return true}catch(e){setSaveError((options.pessimistic?'导入失败：':'保存失败：')+e.message+'。原有记录已保留，请重试刚才的操作。');notify('保存失败：'+e.message);return false}finally{pending.current--;if(!pending.current)setSaving(false)}});queue.current=task;return task;
 },[notify]);
 const go=page=>{navigateInsight(page);setMobileOpen(false)},openArticle=id=>go('article/'+id),onCategory=id=>{setCategory(id);go('explore')};
 const activity=(type,extra={})=>({id:crypto.randomUUID(),type,date:new Date().toISOString(),day:dayKey(),...extra});
 const bookmark=id=>persist(s=>({...s,bookmarks:s.bookmarks.includes(id)?s.bookmarks.filter(v=>v!==id):[...s.bookmarks,id]}));
 const complete=id=>{let already=false;persist(s=>{already=s.completed.includes(id);return {...s,completed:already?s.completed.filter(v=>v!==id):[...s.completed,id],activity:already?s.activity:[activity('learn',{articleId:id}),...s.activity]}}).then(ok=>ok&&notify(already?'已取消学完标记':'已记录到学习档案'))};
 const activeArticle=articles.find(a=>a.id===route.id);
 return <div className="app-shell">{mobileOpen&&<button className="sidebar-backdrop" aria-label="关闭导航" onClick={()=>setMobileOpen(false)}/>}<aside className={'sidebar '+(mobileOpen?'is-open':'')}><a className="brand" href="#today"><span className="brand-mark"><i/><i/><i/><i/></span><span>InsightMatrix<small>认知矩阵</small></span></a><div className="workspace-label">个人认知工作台<span>PERSONAL</span></div><nav>{nav.map(n=><button key={n.id} className={'nav-item '+(route.page===n.id||(route.page==='article'&&n.id==='explore')?'active':'')} onClick={()=>go(n.id)}><n.icon size={19}/><span>{n.label}</span>{n.id==='today'&&<span className="nav-dot"/>}{n.id==='theses'&&state.theses.length>0&&<small>{state.theses.length}</small>}</button>)}</nav><div className="sidebar-separator"/><div className="sidebar-label">六个视角，一个世界</div><div className="sidebar-categories">{categories.map(c=><button key={c.id} onClick={()=>onCategory(c.id)}><span style={{background:c.color}}/>{c.label}<ChevronRight size={12}/></button>)}</div><div className="sidebar-bottom"><div className="sidebar-quote"><span className="quote-mark">“</span><p>真正的发现之旅，<br/>在于拥有新的眼光。</p><small>让每一次思考，都留下痕迹。</small></div><button className="profile-button" onClick={()=>go('profile')}><span className="avatar">知</span><span>终身学习者<small>保持好奇，独立判断</small></span><Settings2 size={17}/></button></div></aside>
 <main className="main-workspace"><header className="topbar"><div className="breadcrumb"><button className="icon-button mobile-menu" aria-label="打开导航" onClick={()=>setMobileOpen(true)}><Menu size={20}/></button><span>我的工作台</span><ChevronRight size={13}/><strong>{route.page==='article'?'深度阅读':nav.find(n=>n.id===route.page)?.label}</strong></div><div className="topbar-actions"><button className="search-trigger" onClick={()=>setSearchOpen(true)}><Search size={16}/><span>搜索概念、案例、问题</span><kbd>Ctrl K</kbd></button><span className="local-indicator"><i/>{saving?'正在保存':saveError?'待同步':'本地工作空间'}</span><span className="top-avatar">知</span></div></header><div className="content-wrap">{saveError&&<div className="error-banner" role="alert">{saveError}<button onClick={()=>setSaveError('')}>知道了</button></div>}{loading?<div className="loading-state"><span className="loading-orbit"/><h2>正在打开你的认知工作台</h2><p>连接知识，积累判断。</p></div>:error?<Empty icon={BookOpen} title="暂时无法打开工作台" text={error} action="重新加载" onAction={load}/>:<>
 {route.page==='today'&&<Dashboard articles={articles} state={state} today={today} question={question} questionId={questionId} onChallenge={()=>setChallengeOpen(true)} onNewThesis={()=>setEditor({})} go={go} onOpen={openArticle} onBookmark={bookmark} onCategory={onCategory}/>}
 {(route.page==='explore'||route.page==='cases')&&<Library key={route.page} type={route.page==='cases'?'case':'concept'} articles={articles} state={state} category={category} setCategory={setCategory} onOpen={openArticle} onBookmark={bookmark}/>}
 {route.page==='article'&&(activeArticle?<ArticleReader article={activeArticle} articles={articles} state={state} onOpen={openArticle} onBookmark={bookmark} onComplete={complete} onBack={()=>go(activeArticle.type==='case'?'cases':'explore')} onThesis={()=>setEditor({sourceId:activeArticle.id})}/>:<Empty icon={BookOpen} title="这篇内容暂未找到" text="返回知识探索，打开一个新的思考入口。" action="探索知识" onAction={()=>go('explore')}/>)}
 {route.page==='graph'&&<Graph articles={articles} onOpen={openArticle}/>}
 {route.page==='theses'&&<Theses theses={state.theses} onNew={()=>setEditor({})} onEdit={setEditor} onReview={setReview} onDelete={id=>persist(s=>({...s,theses:s.theses.filter(t=>t.id!==id)}))}/>}
 {route.page==='profile'&&<Profile state={state} articles={articles} onOpen={openArticle} onBookmark={bookmark} persist={persist} notify={notify}/>}
 <footer className="footer"><span><span className="footer-mark">✳</span>InsightMatrix · 认知矩阵</span><span>把知识变成理解，把理解变成判断。</span><small>为独立思考而设计</small></footer></>}</div></main>
 {searchOpen&&<SearchModal articles={articles} onClose={()=>setSearchOpen(false)} onOpen={id=>{setSearchOpen(false);openArticle(id)}}/>}
 {challengeOpen&&<Challenge key={questionId} question={question} questionId={questionId} answer={state.answers[questionId]} onClose={()=>setChallengeOpen(false)} onSave={async text=>{const ok=await persist(s=>({...s,answers:{...s.answers,[questionId]:{text,question:question.title,savedAt:new Date().toISOString()}},activity:[activity('challenge'),...s.activity]}));if(ok)notify('思考已保存');return ok}} onExplore={()=>{setChallengeOpen(false);go('explore')}}/>}
 {editor&&<ThesisForm thesis={editor} onClose={()=>setEditor(null)} onSave={async data=>{const exists=!!editor.id,snapshot={title:data.title,judgement:data.judgement,evidence:data.evidence,counterEvidence:data.counterEvidence,falsification:data.falsification,probability:data.probability,deadline:data.deadline};const saved={...editor,...data,id:editor.id||crypto.randomUUID(),createdAt:editor.createdAt||new Date().toISOString(),updatedAt:new Date().toISOString(),original:editor.original||snapshot};const ok=await persist(s=>({...s,theses:exists?s.theses.map(t=>t.id===saved.id?saved:t):[saved,...s.theses],activity:[activity('thesis'),...s.activity]}));if(ok){setEditor(null);notify(exists?'判断已更新，初始记录已保留':'判断已保存，未来可以回来验证');go('theses')}}}/>}
 {review&&<ReviewForm thesis={review} onClose={()=>setReview(null)} onSave={async data=>{const ok=await persist(s=>({...s,theses:s.theses.map(t=>t.id===review.id?{...t,reviews:[...(t.reviews||[]),{...data,id:crypto.randomUUID(),date:new Date().toISOString()}]}:t),activity:[activity('review'),...s.activity]}));if(ok){setReview(null);notify('复盘已保存，原始判断与概率保持不变')}}}/>}
 <BackToTop />
 {toast&&<div className="toast" role="status"><CheckCircle2 size={18}/>{toast}</div>}
 </div>
}
