import React,{useState} from 'react';
import {Search,ArrowLeft,ArrowUpRight,ArrowRight,BookOpen,Bookmark,Clock3,Check,CheckCircle2,Feather,GitBranch,Network} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import {categories,categoryOf} from './data';
import {Intro,Empty,ArticleCard,Modal} from './ui';
export function Library({type,articles,state,category,setCategory,onOpen,onBookmark}){
 const [query,setQuery]=useState(''),[filter,setFilter]=useState('all');
 const filtered=articles.filter(a=>a.type===type&&(category==='all'||a.category===category)&&(filter!=='bookmarked'||state.bookmarks.includes(a.id))&&(filter!=='unread'||!state.completed.includes(a.id))&&[a.title,a.summary,a.tags?.join(' '),a.body].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <><Intro eyebrow={type==='case'?'PATTERNS THROUGH HISTORY':'YOUR MENTAL TOOLBOX'} title={type==='case'?'以历史为镜，理解变化的机制':'让零散的知识，长成理解'} description={type==='case'?'把概念放回历史现场。分清事实、机制与事后解释，避免把类比当成预测。':'从人性到投资，建立相互连接的思维工具。每个概念都有机制、边界与实践。'}/><div className="library-toolbar"><div className="category-tabs"><button className={category==='all'?'active':''} onClick={()=>setCategory('all')}>全部视角</button>{categories.map(c=><button key={c.id} className={category===c.id?'active':''} onClick={()=>setCategory(c.id)}>{c.label}</button>)}</div><label className="inline-search"><Search size={16}/><input placeholder="搜索标题与正文…" value={query} onChange={e=>setQuery(e.target.value)}/></label></div><div className="library-subbar"><span>共 <strong>{filtered.length}</strong> 篇{type==='case'?'历史案例':'核心概念'}</span><div className="segmented">{[['all','全部'],['unread','未学完'],['bookmarked','已收藏']].map(([id,label])=><button key={id} className={filter===id?'active':''} onClick={()=>setFilter(id)}>{label}</button>)}</div></div>{filtered.length?<div className="article-grid library-grid">{filtered.map(a=><ArticleCard key={a.id} article={a} state={state} onOpen={onOpen} onBookmark={onBookmark}/>)}</div>:<Empty icon={Search} title="没有找到匹配的内容" text="试试其他关键词，或者查看全部知识。" action="清除筛选" onAction={()=>{setQuery('');setCategory('all');setFilter('all')}}/>}</>
}
export function ArticleReader({article:a,articles,state,onOpen,onBookmark,onComplete,onBack,onThesis}){
 const c=categoryOf(a.category),related=(a.related||[]).map(id=>articles.find(x=>x.id===id)).filter(Boolean);
 return <div className="reader-layout"><article className="reader"><button className="text-button reader-back" onClick={onBack}><ArrowLeft size={16}/>返回{a.type==='case'?'历史案例':'知识探索'}</button><span className="category-label" style={{color:c.color}}><c.icon size={16}/>{c.label} / {a.type==='case'?'历史案例':'核心概念'}</span><h1>{a.title}</h1><p className="reader-summary">{a.summary}</p><div className="reader-meta"><span><Clock3 size={14}/>{a.minutes} 分钟阅读</span><span>{a.difficulty||'基础'}</span>{state.completed.includes(a.id)&&<span className="completed-label"><CheckCircle2 size={14}/>已学完</span>}<button className="text-button" onClick={()=>onBookmark(a.id)}><Bookmark size={15} fill={state.bookmarks.includes(a.id)?'currentColor':'none'}/>{state.bookmarks.includes(a.id)?'已收藏':'收藏'}</button></div><div className="markdown-body"><ReactMarkdown remarkPlugins={[remarkGfm]} components={{a:({node,...props})=><a {...props} target="_blank" rel="noopener noreferrer"/>}}>{a.body}</ReactMarkdown></div><div className="reader-end"><span className="eyebrow">理解的下一步，是尝试运用。</span><h3>它能改变你的哪一个判断？</h3><p>写下一个具体场景，记录支持和反对的证据。</p><div className="button-row"><button className="button primary" onClick={onThesis}><Feather size={16}/>用这个概念写判断</button><button className="button secondary" onClick={()=>onComplete(a.id)}><Check size={16}/>{state.completed.includes(a.id)?'取消学完标记':'标记为已学完'}</button></div></div></article><aside className="reader-sidebar"><div className="reader-side-card"><div className="eyebrow">READ · CONNECT · APPLY</div><h3>不是记住一个词，<br/>而是多一个看法。</h3><p>读完后，尝试用自己的话回答：</p><ul><li>它解释了什么现象？</li><li>它在什么条件下失效？</li><li>什么证据会改变我的看法？</li></ul></div><section className="related-card"><h3><GitBranch size={17}/>连接着这些知识</h3>{related.map(x=><button key={x.id} onClick={()=>onOpen(x.id)}><span><small>{categoryOf(x.category).label}</small>{x.title}</span><ArrowUpRight size={15}/></button>)}</section><div className="tag-list">{a.tags?.map(t=><span key={t}>#{t}</span>)}</div></aside></div>
}
export function SearchModal({articles,onClose,onOpen}){
 const [query,setQuery]=useState('');const result=articles.filter(a=>[a.title,a.summary,a.tags?.join(' '),a.body].join(' ').toLowerCase().includes(query.toLowerCase())).slice(0,20);
 return <Modal onClose={onClose} label="搜索知识"><div className="search-modal-input"><Search size={23}/><input placeholder="搜索一个概念、问题或关键词…" value={query} onChange={e=>setQuery(e.target.value)}/></div><div className="search-results-label">{query?'找到 '+result.length+(result.length===20?'+':'')+' 条相关内容':'从一个关键词开始，也可以直接探索'}</div><div className="search-results">{result.length?result.map(a=><button key={a.id} onClick={()=>onOpen(a.id)}><span className="search-result-icon"><BookOpen size={18}/></span><span><strong>{a.title}</strong><small>{categoryOf(a.category).label} · {a.type==='case'?'历史案例':'核心概念'} · {a.summary}</small></span><ArrowUpRight size={16}/></button>):<p className="search-empty">没有找到匹配内容，试试“激励”“概率”或“周期”。</p>}</div><div className="search-modal-footer"><span>搜索覆盖标题、摘要、标签和全文</span><kbd>ESC 关闭</kbd></div></Modal>
}
export function Graph({articles,onOpen}){
 const [selected,setSelected]=useState('all'),[focus,setFocus]=useState(null),nodes=articles.filter(a=>a.type==='concept'&&(selected==='all'||a.category===selected)),item=articles.find(a=>a.id===focus);
 const placed=nodes.map((a,i)=>{const angle=i/nodes.length*Math.PI*2-Math.PI/2,r=nodes.length<10?215:(i%2?245:165);return {...a,x:430+Math.cos(angle)*r,y:325+Math.sin(angle)*r}});
 return <><Intro eyebrow="CONNECTED KNOWLEDGE" title="好的判断，来自知识之间的连接" description="从一个概念出发，看见它与其他领域的关联。点击节点查看关系，再进入深度阅读。"/><div className="category-tabs graph-tabs"><button className={selected==='all'?'active':''} onClick={()=>{setSelected('all');setFocus(null)}}>全景图谱</button>{categories.map(c=><button key={c.id} className={selected===c.id?'active':''} onClick={()=>{setSelected(c.id);setFocus(null)}}>{c.label}</button>)}</div><div className="graph-layout"><div className="graph-canvas"><div className="graph-canvas-caption"><Network size={16}/>认知网络<span>{nodes.length} 个概念</span></div><svg viewBox="0 0 860 650" className="knowledge-svg" aria-label="可交互知识概念网络"><circle cx="430" cy="325" r="280" fill="#edf4ef"/><circle cx="430" cy="325" r="235" className="graph-ring"/><circle cx="430" cy="325" r="140" className="graph-ring"/>{placed.map(a=><g key={a.id}>{(a.related||[]).map(id=>{const b=placed.find(n=>n.id===id);return b?<line key={id} x1={a.x} y1={a.y} x2={b.x} y2={b.y} className={'graph-edge '+(focus===a.id||focus===b.id?'lit':'')}/>:null})}</g>)}<circle cx="430" cy="325" r="48" fill="#1f594b"/><text x="430" y="321" textAnchor="middle" fill="white" fontSize="15">独立判断</text><text x="430" y="342" textAnchor="middle" fill="#b7d5c8" fontSize="8" letterSpacing="2">INSIGHT MATRIX</text>{placed.map(a=><g key={a.id} tabIndex="0" role="button" aria-label={'查看关联：'+a.title} onClick={()=>setFocus(a.id)} onKeyDown={e=>(e.key==='Enter'||e.key===' ')&&(e.preventDefault(),setFocus(a.id))} className={'graph-node '+(focus===a.id?'selected':'')}><circle cx={a.x} cy={a.y} r={focus===a.id?10:7} fill={categoryOf(a.category).color}/><circle cx={a.x} cy={a.y} r="15" fill="transparent" stroke={focus===a.id?categoryOf(a.category).color:'transparent'}/><text x={a.x} y={a.y+29} textAnchor="middle" fill="#40584e" fontSize={nodes.length>20?'11':'14'}>{a.title.length>10?a.title.slice(0,9)+'…':a.title}</text></g>)}</svg><div className="graph-legend">{categories.map(c=><span key={c.id}><i style={{background:c.color}}/>{c.label}</span>)}</div></div><aside className="graph-detail">{item?<><div className="eyebrow">{categoryOf(item.category).label} / 概念关系</div><h2>{item.title}</h2><p>{item.summary}</p><button className="button primary" onClick={()=>onOpen(item.id)}>深入理解<ArrowUpRight size={16}/></button><h3>相连的知识</h3>{(item.related||[]).map(id=>articles.find(a=>a.id===id)).filter(Boolean).map(a=><button className="graph-related" key={a.id} onClick={()=>onOpen(a.id)}><span><small>{categoryOf(a.category).label}</small>{a.title}</span><ArrowUpRight size={15}/></button>)}</>:<><span className="graph-detail-icon"><GitBranch size={28}/></span><h2>知识的价值，<br/>在连接中生长。</h2><p>选择一个概念，看看它如何与人性、经济和投资决策相互关联。</p>{['点击节点，查看概念与关联','阅读机制，理解适用边界','回到现实，写下你的判断'].map((s,i)=><div className="graph-instruction" key={s}><span>{'0'+(i+1)}</span>{s}</div>)}</>}</aside></div></>
}
