import React,{useEffect,useRef} from 'react';
import {ArrowUpRight,ArrowRight,Bookmark,Clock3,CheckCircle2,X,Network,GitBranch} from 'lucide-react';
import {categories,categoryOf,dayKey} from './data';
export function Intro({eyebrow,title,description,children}){return <section className="page-intro"><div><div className="eyebrow"><span className="tiny-line"/>{eyebrow}</div><h1>{title}<span className="heading-dot">。</span></h1><p>{description}</p></div>{children}</section>}
export function Empty({icon:Icon,title,text,action,onAction}){return <div className="empty-state"><span className="empty-icon"><Icon size={30}/></span><h2>{title}</h2><p>{text}</p>{action&&<button className="button primary" onClick={onAction}>{action}<ArrowRight size={16}/></button>}</div>}
export function ArticleCard({article:a,state,onOpen,onBookmark}){const c=categoryOf(a.category);return <article className="article-card"><div className="article-card-top"><span className="category-label" style={{color:c.color}}><c.icon size={14}/>{c.label}<i/>{a.type==='case'?'历史案例':'核心概念'}</span><button className={'icon-button bookmark-button '+(state.bookmarks.includes(a.id)?'selected':'')} aria-label={(state.bookmarks.includes(a.id)?'取消收藏：':'收藏：')+a.title} onClick={()=>onBookmark(a.id)}><Bookmark size={17} fill={state.bookmarks.includes(a.id)?'currentColor':'none'}/></button></div><button className="article-card-content" onClick={()=>onOpen(a.id)}><h3>{a.title}</h3><p>{a.summary}</p></button><div className="article-card-bottom"><span><Clock3 size={13}/>{a.minutes||6} 分钟<i/>{a.difficulty||'基础'}</span><button onClick={()=>onOpen(a.id)} aria-label={'阅读：'+a.title}>{state.completed.includes(a.id)?<CheckCircle2 size={17}/>:<ArrowUpRight size={17}/>}</button></div></article>}
export function ActivityHeatmap({activity}){const counts={};activity.forEach(a=>{const d=a.day||(a.date?dayKey(new Date(a.date)):null);if(d)counts[d]=(counts[d]||0)+1});return <div className="heatmap-wrap"><div className="heatmap" aria-label="最近 70 天的学习活动">{Array.from({length:70},(_,i)=>{const date=new Date();date.setDate(date.getDate()-(69-i));const key=dayKey(date);return <span key={i} title={key+'：'+(counts[key]||0)+' 次活动'} style={{background:counts[key]?counts[key]>2?'#36806a':'#99bfae':undefined}}/>})}</div><div className="heatmap-legend"><span>最近 10 周</span><span>少 <i/><i/><i/> 多</span></div></div>}
export function OrbitArt({onCategory}){return <div className="orbit-art" aria-label="六个知识领域互相连接"><svg className="orbit-lines" viewBox="0 0 380 340" aria-hidden="true"><defs><radialGradient id="orbGlow"><stop offset="0" stopColor="#b8d4c5" stopOpacity=".65"/><stop offset="1" stopColor="#dce9e2" stopOpacity="0"/></radialGradient></defs><circle cx="190" cy="170" r="164" fill="url(#orbGlow)"/><ellipse cx="190" cy="170" rx="143" ry="127"/><ellipse cx="190" cy="170" rx="94" ry="145" transform="rotate(55 190 170)"/><ellipse cx="190" cy="170" rx="94" ry="145" transform="rotate(-55 190 170)"/><circle cx="190" cy="170" r="80" strokeDasharray="2 7"/>{[[190,42],[308,102],[308,235],[190,295],[70,235],[70,102]].map(([x,y],i)=><line key={i} x1="190" y1="170" x2={x} y2={y}/>)}<circle cx="150" cy="55" r="3" fill="#82aa91"/><circle cx="330" cy="165" r="4" fill="#bba570"/></svg><div className="orbit-core"><Network size={30} strokeWidth={1.2}/><strong>独立判断</strong><small>THINK IN SYSTEMS</small></div>{categories.map((c,i)=><button key={c.id} className={'orbit-node orbit-node-'+i} onClick={()=>onCategory(c.id)}><c.icon size={16} style={{color:c.color}}/>{c.label}</button>)}</div>}
export function Modal({children,onClose,label,wide=false}){const ref=useRef(null);useEffect(()=>{const previous=document.activeElement,old=document.body.style.overflow;document.body.style.overflow='hidden';const node=ref.current;node.querySelector('input,textarea,button')?.focus();const trap=e=>{if(e.key==='Escape'){e.stopPropagation();onClose();return}if(e.key!=='Tab')return;const items=[...node.querySelectorAll('button:not([disabled]),input:not([disabled]),textarea,select,a[href]')],first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus()}};node.addEventListener('keydown',trap);return()=>{document.body.style.overflow=old;node.removeEventListener('keydown',trap);previous?.focus()}},[]);return <div className="modal-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className={'modal '+(wide?'modal-wide':'')} ref={ref} role="dialog" aria-modal="true" aria-label={label}><button className="modal-close icon-button" aria-label="关闭" onClick={onClose}><X size={21}/></button>{children}</section></div>}
