import { createServer } from 'vite';
import { fileURLToPath } from 'node:url';
import { writeFile } from 'node:fs/promises';
import { format } from 'prettier';

const root = fileURLToPath(new URL('../', import.meta.url));
const server = await createServer({
  root,
  server: { middlewareMode: true },
  appType: 'custom',
});
try {
  const { lessons, lessonCollections } = await server.ssrLoadModule(
    '/src/content/lessons.ts',
  );
  const { catalogEntry } = await server.ssrLoadModule(
    '/src/content/catalogEntry.ts',
  );
  const entries = lessons.map((lesson) => {
    const packs = Object.entries(lessonCollections).filter(([, group]) =>
      group.some((l) => l.id === lesson.id),
    );
    if (packs.length !== 1)
      throw new Error(
        `Expected one content pack for ${lesson.id}, found ${packs.length}`,
      );
    return catalogEntry(lesson, packs[0][0]);
  });
  const text =
    '// Generated by scripts/update-catalog.mjs. Edit lesson content, then regenerate.\n' +
    "import type { LessonCatalogEntry } from './catalogEntry';\n" +
    `export const lessonCatalog: LessonCatalogEntry[] = ${JSON.stringify(entries, null, 2)};\n`;
  await writeFile(
    new URL('../src/content/catalog.ts', import.meta.url),
    await format(text, {
      parser: 'typescript',
      singleQuote: true,
      trailingComma: 'all',
    }),
  );
  console.log(
    `Updated catalog: ${entries.length} lessons; ${Object.keys(lessonCollections).length} content packs.`,
  );
} finally {
  await server.close();
}
