// A course is a sustained unit of study. A lesson is planned until its Markdown
// file exists and passes content validation; planned entries never count as done.
const course = (level, order, id, title, titleEn, description, competency, artifact, lessons) => ({
  level, order, id, title, titleEn, description, competency, artifact,
  lessons: lessons.map(([lessonId, lessonTitle, focus], index) => ({
    id: lessonId, title: lessonTitle, focus, order: index + 1,
  })),
});

export const levels = [
  { id: 1, title: '方法与基础', titleEn: 'Foundations', question: '怎样提出、重建和检验一个哲学论证？' },
  { id: 2, title: '哲学史与传统', titleEn: 'Histories & Traditions', question: '不同传统如何形成并争论今天仍在场的问题？' },
  { id: 3, title: '核心领域与交叉问题', titleEn: 'Core Fields', question: '知识、现实、价值、语言与制度的主要理论如何互相制约？' },
  { id: 4, title: '专题研讨与独立研究', titleEn: 'Seminars & Capstone', question: '能否在原典、文献和强反对意见面前捍卫自己的论题？' },
];

export const syllabusCourses = [
  course(1, 1, 'introduction-to-philosophy', '哲学导论', 'Introduction to Philosophy',
    '从概念、问题和论证进入哲学；理解分歧为什么仍可理性推进。',
    '辨认哲学问题，区分事实、概念与规范判断，公平重建简短论证。',
    '写一篇 800–1200 字的立场说明，包含一个反例和一次修订。', [
      ['what-is-philosophy', '什么是哲学？', '区分基本问题、经验调查与有理由的探究'],
      ['argument-vs-opinion', '观点与论证', '找出理由、结论及主张的适用范围'],
      ['concepts-and-questions', '概念澄清与好问题', '辨认歧义，提出可推进的哲学问题'],
      ['premises-and-inference', '前提、结论与推理', '把散文改写成可检查的论证'],
      ['thought-experiments', '思想实验能证明什么？', '分析案例直觉的作用与局限'],
      ['reading-primary-text', '怎样细读哲学原典', '区分作者原话、解释与个人评价'],
      ['disagreement-and-charity', '分歧与善意解释', '重述最强版本并定位真正争点'],
      ['first-philosophical-position', '第一次提出并修订立场', '综合论证、反例、回应与保留意见'],
    ]),
  course(1, 2, 'critical-thinking', '批判性思维与非形式逻辑', 'Critical Thinking',
    '让日常推理变得可拆解、可质疑、可改进。',
    '区分演绎与归纳、有效与健全，识别隐藏前提并使用反例。',
    '对一篇公共论说提交论证图、最强反对意见与改写版。', [
      ['anatomy-of-an-argument', '论证的结构', '区分前提、结论与解释性背景'],
      ['deduction-and-induction', '演绎、归纳与溯因', '按支持关系而非语气分类推理'],
      ['validity-and-soundness', '有效性与健全性', '用反例区分形式缺陷与前提问题'],
      ['hidden-premises', '隐藏前提与原则', '补出必要前提并评估其代价'],
      ['counterexamples', '反例与论题修订', '构造相关反例并避免偷换命题'],
      ['fallacies-and-causation', '谬误、类比与因果', '判断何时真有推理缺陷'],
      ['evidence-and-testimony', '证据与证言', '校准证据强度和来源可靠性'],
      ['argument-map', '论证图与最终改写', '把复杂争论拆为可辩护的步骤'],
    ]),
  course(1, 3, 'formal-logic', '形式逻辑', 'Formal Logic',
    '用符号语言精确检查推理，同时理解形式化的边界。',
    '翻译命题，使用真值表和证明，辨认量词、同一性与反模型。',
    '完成一套翻译、证明、反模型与错误诊断题。', [
      ['statements-and-form', '命题与逻辑形式', '区分真值承担者和自然语言歧义'],
      ['connectives', '否定、合取、析取与条件', '准确翻译复合命题'],
      ['truth-tables', '真值表与语义蕴涵', '用赋值判定重言式和有效性'],
      ['natural-deduction', '自然演绎入门', '逐步证明基本命题逻辑推理'],
      ['quantifiers', '全称、存在与论域', '翻译并检验一阶量词句'],
      ['identity-and-scope', '同一性与量词辖域', '识别多重量词的歧义'],
      ['proofs-and-countermodels', '证明与反模型', '在证明失败时构造模型'],
      ['limits-of-formalization', '形式化的哲学边界', '区分有效性、前提真实性与概念选择'],
    ]),
  course(1, 4, 'philosophical-writing', '哲学阅读与写作', 'Philosophical Reading & Writing',
    '把清晰的思考写成经得起反对意见的文章。',
    '准确解释原文、提出窄而可辩护的论题、修订论证。',
    '提交 1500–2500 字论文、论证提纲、批注书目和修订记录。', [
      ['a-defensible-thesis', '提出可辩护的论题', '把宽泛话题变成精确主张'],
      ['charitable-exposition', '忠实解释他人的观点', '分开转述、推断与评价'],
      ['reconstructing-a-text', '从原典重建论证', '用段落证据支持解释'],
      ['strong-objections', '写出最强反对意见', '攻击关键前提而非弱化对手'],
      ['replies-and-concessions', '回应、让步与修改', '辨认有代价的回应'],
      ['sources-and-citations', '来源、引文与学术诚信', '核对版本、页码与解释归属'],
      ['draft-and-revision', '提纲、初稿与结构性修订', '以读者可追踪的方式重排论证'],
      ['first-essay-workshop', '短论文工作坊', '依据评阅标准重写并说明改动'],
    ]),
  course(2, 1, 'ancient-greek-philosophy', '古希腊与希腊化哲学', 'Ancient Greek Philosophy',
    '从苏格拉底的追问到希腊化学派的生活论证。',
    '在原典语境中重建柏拉图、亚里士多德与希腊化思想的核心论证。',
    '比较两种关于德性或知识的理论，提交原典细读论文。', [
      ['socratic-examination', '苏格拉底的诘问', '分析反诘法能揭示什么'],
      ['euthyphro', '《欧绪弗洛》与定义难题', '重建虔敬困境并辨认其范围'],
      ['meno', '《美诺》：德性与学习', '评估探究悖论与回忆说'],
      ['republic-justice', '《理想国》：正义与城邦', '比较正义的工具价值与内在价值'],
      ['aristotle-demonstration', '亚里士多德的解释与证明', '区分逻辑结构和知识的原因'],
      ['aristotle-virtue', '亚里士多德的德性伦理', '重建幸福、习惯与明智的关系'],
      ['epicurus-and-stoics', '伊壁鸠鲁与斯多亚学派', '比较快乐、宁静与可控之事'],
      ['ancient-skepticism', '古代怀疑主义', '比较悬搁判断与求知承诺'],
    ]),
  course(2, 2, 'classical-asian-philosophy', '中国与南亚古典哲学', 'Classical Chinese & South Asian Philosophy',
    '在各自文本与辩论传统中研究人、知识、秩序与解脱。',
    '避免以西方概念强行套译，准确比较儒墨道与南亚论证传统。',
    '对一个跨传统问题写带有术语翻译说明的比较论文。', [
      ['analects-ren-li', '《论语》：仁、礼与成德', '分析规范如何通过实践形成'],
      ['mencius-xunzi', '孟子与荀子的人性之辩', '区分人性论与教育论的前提'],
      ['mozi-impartial-care', '墨子：兼爱与公共理由', '重建兼爱论证及其代价'],
      ['zhuangzi-perspectives', '《庄子》：视角与判断', '避免把齐物论误读成简单相对主义'],
      ['nyaya-knowledge', '正理派：知识来源与论证', '比较知觉、推理与证言的地位'],
      ['buddhist-no-self', '佛教无我与缘起', '重建自我批评及其修行背景'],
      ['madhyamaka-emptiness', '中观：空性与二谛', '区分空性与虚无主义'],
      ['cross-tradition-self', '跨传统比较：自我与关系', '提出谨慎的可比性论证'],
    ]),
  course(2, 3, 'medieval-philosophy', '古代晚期与中世纪哲学', 'Late Antique & Medieval Philosophy',
    '在基督教、伊斯兰与犹太传统的交会处研究存在、因果与信仰。',
    '标出神学前提，并独立评估相关哲学推理。',
    '比较两个传统对同一问题的论证与隐藏前提。', [
      ['augustine-evil', '奥古斯丁：恶与意志', '评估恶为善之缺失的主张'],
      ['avicenna-being', '伊本·西那：必然存在者', '重建可能与必然的推理'],
      ['ghazali-averroes', '安萨里与伊本·鲁世德：因果', '区分习惯、必然与自然解释'],
      ['maimonides-language', '迈蒙尼德：否定神学', '检验语言对超越者的限制'],
      ['anselm-aquinas', '安瑟伦与阿奎那：存在论证', '比较两类论证的结构'],
      ['universals-medieval', '共相争论', '辨认实在论与唯名论的代价'],
      ['natural-law-medieval', '自然法与实践理性', '分析目的论的规范力量'],
      ['faith-and-reason-medieval', '信仰与理性的边界', '分辨启示前提和公共论证'],
    ]),
  course(2, 4, 'early-modern-philosophy', '早期近代哲学', 'Early Modern Philosophy',
    '跟随笛卡尔到休谟，检验心灵、实体、经验与因果。',
    '把原典中的认识论与形而上学主张重建为清楚的论证。',
    '提交“知识从何而来”原典比较与反对意见。', [
      ['descartes-doubt', '笛卡尔：方法性怀疑', '区分方法与永久怀疑'],
      ['cogito', '我思与自我确定性', '评估我思能证明到哪一步'],
      ['cartesian-dualism', '身心二元论与互动难题', '重建可分离性论证'],
      ['spinoza-substance', '斯宾诺莎：实体与必然性', '解释一元论的推理结构'],
      ['locke-ideas', '洛克：观念与经验', '区分第一性质与第二性质'],
      ['berkeley-immaterialism', '贝克莱：存在即被感知？', '评估对物质实体的批评'],
      ['hume-causation', '休谟：因果与归纳', '区分恒常联结和必然联系'],
      ['hume-self', '休谟：自我与怀疑', '检查知觉束与持续自我的关系'],
    ]),
  course(2, 5, 'enlightenment-nineteenth-century', '康德、启蒙与十九世纪', 'Kant & Nineteenth Century',
    '从批判哲学走向自由、历史、功利与价值重估。',
    '读懂康德的限制性主张，并公平比较其后继者与批评者。',
    '围绕自由或道德写一篇多作者比较论文。', [
      ['kant-synthetic-apriori', '康德：先天综合判断', '解释康德的问题如何回应经验论'],
      ['kant-categories', '范畴与经验的条件', '区分现象、物自身与不可知的范围'],
      ['kant-ethics', '定言令式与自主', '检验普遍化测试的解释'],
      ['hegel-recognition', '黑格尔：承认与历史', '避免把辩证法压成三段公式'],
      ['bentham-mill', '边沁与密尔：效用与自由', '辨认两人的论证差异'],
      ['kierkegaard-existence', '克尔凯郭尔：存在与选择', '分析主观性主张的边界'],
      ['marx-alienation', '马克思：异化与批判', '区分经济解释与规范批评'],
      ['nietzsche-genealogy', '尼采：谱系与价值', '评估谱系解释能否反驳规范'],
    ]),
  course(2, 6, 'twentieth-century-traditions', '二十世纪哲学传统', 'Twentieth-Century Traditions',
    '理解分析、现象学、存在主义、实用主义与批判理论的不同方法。',
    '准确指出方法之争中的共同问题和真正差异。',
    '写一篇跨传统比较，明确其可比性限制。', [
      ['frege-russell', '弗雷格与罗素：分析转向', '区分意义、指称与描述问题'],
      ['wittgenstein-two-periods', '维特根斯坦的两种方法', '比较图像说和语言游戏'],
      ['logical-empiricism', '逻辑经验主义及其困难', '检验可证实性标准的自我适用'],
      ['husserl-phenomenology', '胡塞尔：意向性与现象学', '区分描述方法与心理学解释'],
      ['existential-phenomenology', '海德格尔、萨特与波伏瓦', '比较处境、自由与他人'],
      ['pragmatism', '皮尔士、詹姆斯与杜威', '区分实用后果和粗糙功利'],
      ['critical-theory', '批判理论与权力', '分析社会批评的规范基础'],
      ['poststructuralism-dialogue', '结构、谱系与跨传统对话', '防止把诸多传统合成单一立场'],
    ]),
  course(3, 1, 'epistemology', '认识论', 'Epistemology',
    '考察知识、辩护、怀疑、证言与理性分歧。',
    '精确比较内部论与外部论，并评估社会情境中的知识主张。',
    '写一篇含反例与理论修订的知识论论文。', [
      ['knowledge-gettier', '知识与盖梯尔问题', '评估“有理由的真信念”及其反例'],
      ['structure-of-justification', '辩护的结构', '比较基础论、融贯论与无穷后退'],
      ['reliabilism', '可靠主义与外部论', '辨认可靠过程和主体可及性的冲突'],
      ['skepticism-context', '怀疑论与语境', '重建怀疑论证并比较回应'],
      ['testimony-and-injustice', '证言、信任与认识不公', '分析社会权力如何影响知识实践'],
      ['epistemic-disagreement', '分歧、德性与知识责任', '检验同侪分歧时应怎样更新信念'],
    ]),
  course(3, 2, 'metaphysics', '形而上学', 'Metaphysics',
    '研究同一性、可能性、因果、时间和对象构成。',
    '使用反例与模态区分，比较竞争性存在论的解释力与代价。',
    '为一个形而上学立场制作论证图与反模型。', [
      ['identity-and-persistence', '同一性与持续', '区分数目同一与性质相似'],
      ['universals-and-properties', '共相、属性与相似', '比较实在论、唯名论与比拟解释'],
      ['possibility-and-necessity', '可能世界与必然性', '说明模态语言的承诺与限制'],
      ['causation-and-laws', '因果、反事实与规律', '比较常规性和干预性解释'],
      ['time-and-change', '时间、变化与现在', '分析时间理论的经验与形而上学代价'],
      ['composition-and-persons', '部分、整体与人格同一', '从组合问题回到人的存续'],
    ]),
  course(3, 3, 'ethics', '伦理学', 'Ethics',
    '从元伦理学到规范伦理学，比较行动、品格与关系。',
    '区分理论的判断标准、决策程序与辩护理由。',
    '用同一复杂案例检验至少三种理论并提出自己的修订立场。', [
      ['moral-reality', '道德判断能否为真？', '比较实在论、建构论与反实在论'],
      ['consequentialism', '后果主义与功利主义', '分析聚合、预测与苛求性'],
      ['deontology', '义务、权利与约束', '检验义务论如何处理冲突'],
      ['virtue-and-care', '德性伦理与关怀伦理', '比较品格、关系与具体情境'],
      ['contractualism', '契约主义与相互辩护', '评估不能合理拒绝的标准'],
      ['moral-luck-case', '道德运气与复杂案例', '在冲突中调整原则而非套公式'],
    ]),
  course(3, 4, 'political-philosophy', '政治哲学', 'Political Philosophy',
    '分析权威、自由、正义、权利与共同决策的正当性。',
    '公平重建竞争性政治立场，区分经验前提与规范前提。',
    '围绕一项公共制度写含最强反方论证的政策哲学论文。', [
      ['authority-and-obligation', '政治权威与服从义务', '评估同意、公共利益与合法性'],
      ['liberty-and-coercion', '自由与强制', '比较消极自由、积极自由及共和主义'],
      ['justice-and-equality', '分配正义与平等', '比较罗尔斯、运气平等主义和充分主义'],
      ['rights-and-property', '权利、财产与市场', '检验权利冲突和起点问题'],
      ['democracy-and-disobedience', '民主与公民抗命', '分析多数决的范围和抗命的条件'],
      ['domination-and-global-justice', '支配、边界与全球正义', '把历史权力结构纳入规范评价'],
    ]),
  course(3, 5, 'philosophy-of-mind', '心灵哲学', 'Philosophy of Mind',
    '研究心理状态、意识、他心与身体的关系。',
    '区分本体论、解释模型和现象学证据。',
    '对一种心灵理论提出最强异议和有代价的回应。', [
      ['mind-body-problem', '身心问题与二元论', '重建互动难题和可分离性论证'],
      ['physicalism-functionalism', '物理主义与功能主义', '区分还原、实现和多重实现'],
      ['conscious-experience', '意识经验与解释鸿沟', '比较知识论证和其回应'],
      ['intentionality', '意向性与内容', '分析思想如何指向世界'],
      ['other-minds', '他心与自我知识', '评估行为、类比与第一人称权威'],
      ['embodied-mind', '具身、延展与机器心灵', '检验心灵边界的不同标准'],
    ]),
  course(3, 6, 'philosophy-of-science', '科学哲学', 'Philosophy of Science',
    '考察科学解释、证据、模型与理论变化。',
    '分开科学史描述、方法规范和形而上学解释。',
    '就一个真实科学争论审查证据、模型假设与价值判断。', [
      ['induction-demarcation', '归纳与科学划界', '比较休谟难题和证伪主义'],
      ['explanation-and-laws', '解释、规律与机制', '区分预测成功与解释成功'],
      ['kuhn-paradigms', '库恩与范式转换', '避免把不可通约误读成不可比较'],
      ['scientific-realism', '科学实在论争论', '比较最佳解释和悲观归纳'],
      ['models-and-probability', '模型、理想化与概率', '评估模型何时可以跨情境使用'],
      ['values-in-science', '科学中的价值与信任', '分析非认识价值的正当位置'],
    ]),
  course(3, 7, 'philosophy-of-language', '语言哲学', 'Philosophy of Language',
    '从指称与意义进入言语行为、语境和理解。',
    '通过具体语句测试理论，区分语义与语用解释。',
    '对一个含指称或语境争议的案例写分析报告。', [
      ['sense-reference', '意义与指称', '重建弗雷格的认知价值问题'],
      ['descriptions-and-names', '摹状词与名称', '比较罗素分析与直接指称'],
      ['meaning-and-use', '意义、规则与使用', '评估语言游戏方法能解决什么'],
      ['speech-acts', '言语行为与会话含意', '区分说了什么和暗示了什么'],
      ['context-and-indexicals', '语境、指示词与隐喻', '找出形式语义的边界'],
      ['private-language', '私人语言与公共标准', '重建私人语言论证的不同解释'],
    ]),
  course(3, 8, 'philosophy-of-religion', '宗教哲学', 'Philosophy of Religion',
    '公平分析有神、无神、不可知与多传统立场的理由。',
    '把信仰前提、经验前提与公开可讨论的论证分开。',
    '对一个宗教哲学争论写双向论证和立场修订。', [
      ['arguments-for-god', '神存在论证的家族', '比较宇宙论、目的论与本体论'],
      ['evil-and-suffering', '恶与苦难', '区分逻辑版、证据版与神义论'],
      ['divine-hiddenness', '神的隐匿与不信', '分析关系性前提及回应'],
      ['miracles-and-evidence', '奇迹、经验与证言', '校准非同寻常主张的证据'],
      ['faith-and-reason', '信仰、理性与语言', '比较信仰主义和证据主义'],
      ['religious-pluralism', '宗教多元与相互理解', '分析互斥真理主张和实践差异'],
    ]),
  course(3, 9, 'aesthetics', '美学与艺术哲学', 'Aesthetics',
    '讨论艺术、解释、品味及作品的伦理关系。',
    '用具体作品检验定义，而非仅罗列流派。',
    '提交一篇对具体作品的哲学分析并回应相反解读。', [
      ['what-is-art', '什么算艺术？', '检验模仿、表达与制度理论'],
      ['beauty-and-taste', '美、品味与判断', '分析主观经验和公共理由的关系'],
      ['representation-expression', '再现、表达与形式', '区分作品属性和观众反应'],
      ['interpretation-intention', '解释与作者意图', '比较意图主义与反意图主义'],
      ['art-and-morality', '艺术与道德', '评估伦理瑕疵何时是审美瑕疵'],
      ['aesthetic-experience', '审美经验的文化语境', '检验普遍性与传统差异'],
    ]),
  course(3, 10, 'comparative-social-philosophy', '比较哲学与社会哲学', 'Comparative & Social Philosophy',
    '在谨慎翻译与具体语境下比较自我、关系、压迫和知识。',
    '能说明概念可比性的条件，并检验自身传统的盲点。',
    '提交跨传统比较论文及“翻译与不可比性”附录。', [
      ['comparative-method', '如何做比较哲学', '避免把他者理论当成本土问题的素材库'],
      ['relational-self', '自我、关系与人格', '比较儒家、佛教与西方人格理论'],
      ['ubuntu-community', 'Ubuntu 与共同体', '辨认非洲哲学内部的分歧'],
      ['epistemic-injustice', '女性主义认识论与认识不公', '分析证言和解释资源的分配'],
      ['social-ontology', '种族、性别与社会本体论', '比较社会建构主张的强弱版本'],
      ['comparative-synthesis', '跨传统问题综合', '提出可反驳、可修订的比较论证'],
    ]),
  course(4, 1, 'free-will-seminar', '自由意志专题研讨', 'Free Will Seminar',
    '在决定论、责任和运气论证之间持续追问。',
    '追踪同一论题的多轮反驳，而非只列阵营。',
    '提交 3000–4500 字研讨论文和口头答辩提纲。', [
      ['alternatives-and-sourcehood', '可另行行动与行动源头', '比较两种自由条件'],
      ['manipulation-and-luck', '操纵论证与运气', '检验相容论的最强挑战'],
      ['responsibility-practices', '责任、谴责与实践', '评估形而上学结论的伦理后果'],
      ['free-will-paper', '自由意志论文工作坊', '修订并捍卫窄而原创的论题'],
    ]),
  course(4, 2, 'consciousness-seminar', '意识专题研讨', 'Consciousness Seminar',
    '集中研究主观经验能否纳入自然解释。',
    '区分可设想性、可能性与解释性缺口。',
    '提交 3000–4500 字论文与反方评阅意见。', [
      ['hard-problem', '意识的“难题”', '辨认问题定义中的预设'],
      ['mary-and-zombies', '玛丽与哲学僵尸', '比较知识论证和可设想性论证'],
      ['illusionism-panpsychism', '幻觉论、泛心论与替代解释', '评估扩张本体论的代价'],
      ['consciousness-paper', '意识论文工作坊', '把反例变成对自己理论的压力测试'],
    ]),
  course(4, 3, 'meaning-and-death-seminar', '意义与死亡专题研讨', 'Meaning & Death Seminar',
    '把死亡的坏处、人生意义与时间视角放在同一场辩论。',
    '避免从心理安慰直接推出形而上学结论。',
    '提交 3000–4500 字论文及立场变化说明。', [
      ['epicurus-and-deprivation', '伊壁鸠鲁与剥夺说', '区分体验损害与机会损失'],
      ['mortality-and-immortality', '有限性与永生思想实验', '检验时间长度和意义的关系'],
      ['accounts-of-meaning', '主观、客观与混合意义论', '比较成就、关系和价值判断'],
      ['meaning-paper', '意义问题论文工作坊', '回应与个人直觉相反的最强论证'],
    ]),
  course(4, 4, 'technology-ai-seminar', '技术与人工智能专题研讨', 'Technology & AI Seminar',
    '研究机器心灵、道德地位、责任和知识基础设施。',
    '让哲学结论接受技术事实和治理制度的双重检验。',
    '提交一篇含概念定义、案例边界和反方意见的公共论文。', [
      ['machine-minds', '机器能否有心灵？', '比较行为、功能与体验标准'],
      ['ai-moral-status', '人工智能的道德地位', '分析不确定性下的对待原则'],
      ['algorithmic-responsibility', '自动化系统的责任归属', '区分设计者、部署者和使用者责任'],
      ['ai-knowledge-and-agency', 'AI 时代的知识与能动性', '检验依赖工具时判断能力如何维持'],
    ]),
  course(4, 5, 'capstone', '毕业研究与答辩', 'Independent Research & Capstone',
    '从可研究的问题出发，完成原典与研究文献支持的独立论证。',
    '能在同行评阅下界定问题、读懂文献、修订论证并承认限制。',
    '提交长篇研究论文、注释书目、版本记录与口头答辩；请外部读者批评。', [
      ['research-question', '研究问题与注释书目', '缩小问题并核对一手与二手材料'],
      ['proposal-and-map', '提案、论证图与反方', '形成有风险的论题和竞争解释'],
      ['draft-and-peer-review', '初稿与同行评阅', '基于最强反对意见作结构性修订'],
      ['defense-and-reflection', '终稿、答辩与反思', '说明论证边界及继续研究的问题'],
    ]),
];
