// Generated by scripts/update-catalog.mjs. Edit lesson content, then regenerate.
import type { LessonCatalogEntry } from './catalogEntry';
export const lessonCatalog: LessonCatalogEntry[] = [
  {
    id: 'physics-everywhere',
    title: {
      zh: '物理无处不在',
      en: 'Physics is everywhere',
    },
    subtitle: {
      zh: '从一颗滚动的球，发现世界的规律。',
      en: 'Discover a pattern in a rolling ball.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'friction',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 2,
      },
    ],
  },
  {
    id: 'ask-a-physicist',
    title: {
      zh: '像物理学家一样提问',
      en: 'Ask like a physicist',
    },
    subtitle: {
      zh: '好问题，是一场实验的开始。',
      en: 'A good question starts an experiment.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'variables',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'observe-explain',
    title: {
      zh: '观察，还是解释？',
      en: 'Observation or explanation?',
    },
    subtitle: {
      zh: '先说发生了什么，再追问为什么。',
      en: 'Describe what happened, then ask why.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'observation',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'what-can-we-measure',
    title: {
      zh: '“太重了”有多重？',
      en: 'How heavy is “too heavy”?',
    },
    subtitle: {
      zh: '给书包、歌曲和铅笔找一个测量办法。',
      en: 'Find ways to measure a bag, a song and a pencil.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'quantities',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
    ],
  },
  {
    id: 'units-make-sense',
    title: {
      zh: '数字换了，绳子变了吗？',
      en: 'Different numbers, same string?',
    },
    subtitle: {
      zh: '24 cm、240 mm 和 0.24 m 的秘密。',
      en: 'The secret of 24 cm, 240 mm and 0.24 m.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'units',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-length',
    title: {
      zh: '给世界一把尺',
      en: 'A ruler for the world',
    },
    subtitle: {
      zh: '从“差不多”，走向有单位的测量。',
      en: 'From “about this much” to a measurement.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'length',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-time',
    title: {
      zh: '一秒很短，怎么量准？',
      en: 'How can we time a tiny interval?',
    },
    subtitle: {
      zh: '数十次摆动，比只数一次更可靠。',
      en: 'Time ten swings instead of just one.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'time',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-mass',
    title: {
      zh: '大块海绵比小块金属重吗？',
      en: 'Is a big sponge heavier than small metal?',
    },
    subtitle: {
      zh: '让天平来判断，别只看大小。',
      en: 'Let a balance decide, not size alone.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'mass',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'measure-temperature',
    title: {
      zh: '感觉冷，就真的更冷吗？',
      en: 'Does feeling colder mean being colder?',
    },
    subtitle: {
      zh: '木头与金属，藏着一个温度谜题。',
      en: 'Wood and metal hide a temperature mystery.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'temperature',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'tables-and-data',
    title: {
      zh: '把发现装进一张表。',
      en: 'Put discoveries into a table.',
    },
    subtitle: {
      zh: '一次结果可能偶然，几次记录才能比较。',
      en: 'Compare repeated records, not one lucky result.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'data',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'simple-graphs',
    title: {
      zh: '一条线，讲一个走路故事。',
      en: 'A line tells a walking story.',
    },
    subtitle: {
      zh: '不是地图，而是时间与路程的关系。',
      en: 'A relationship between time and distance, not a map.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'graph',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'cause-and-effect',
    title: {
      zh: '改了两件事，能找到原因吗？',
      en: 'Two changes: can we identify the cause?',
    },
    subtitle: {
      zh: '把“同时发生”变成值得相信的比较。',
      en: 'Turn “happened together” into a fair comparison.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'fair-test',
    pack: 'discoveries',
    predictionCount: 2,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-ice-floats',
    title: {
      zh: '冰山藏起了多少？',
      en: 'How much of an iceberg is hidden?',
    },
    subtitle: {
      zh: '水面上的小尖尖，不是冰山的全部。',
      en: 'The visible tip is only part of the story.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'floating',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-ships-float',
    title: {
      zh: '同一团泥，能变成船吗？',
      en: 'Can the same clay become a boat?',
    },
    subtitle: {
      zh: '质量没变，形状却改变了能排开的水。',
      en: 'Same mass, different water displacement.',
    },
    minutes: 18,
    stage: 0,
    unit: 'mysteries',
    kind: 'boats',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-balls-bounce',
    title: {
      zh: '球怎么又回来了？',
      en: 'How does the ball come back up?',
    },
    subtitle: {
      zh: '落下、变形、回弹，能量走了一条什么路？',
      en: 'Fall, deform, rebound: follow the energy.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'bounce',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-echoes-return',
    title: {
      zh: '声音走了多远才回来？',
      en: 'How far does an echo travel?',
    },
    subtitle: {
      zh: '一声呼喊，藏着一趟往返旅行。',
      en: 'One call makes a return journey.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'echo',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'why-mirrors-show-us',
    title: {
      zh: '镜子后面真有另一个你吗？',
      en: 'Is another you really behind the mirror?',
    },
    subtitle: {
      zh: '跟随真正的光，看懂“像”的位置。',
      en: 'Follow real light to locate the image.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'mirror',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-balloons-attract',
    title: {
      zh: '墙没带电，气球怎么还靠过来？',
      en: 'Why does a balloon approach a neutral wall?',
    },
    subtitle: {
      zh: '不接触，也能有作用；中性也不是没有电荷。',
      en: 'An interaction without contact; neutral is not charge-free.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'static',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-seatbelts-matter',
    title: {
      zh: '车停了，身体为什么还想向前？',
      en: 'Why does your body keep moving when the car stops?',
    },
    subtitle: {
      zh: '用玩具模型认识惯性与减速作用。',
      en: 'Explore inertia and slowing with a toy model.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'seatbelt',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-volume',
    title: {
      zh: '石头没有直边，怎么量大小？',
      en: 'No straight edges: how big is the stone?',
    },
    subtitle: {
      zh: '让水帮你量出占据的空间。',
      en: 'Let water reveal the space it occupies.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'volume',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'accuracy-and-resolution',
    title: {
      zh: '每次都一样，就一定量对了吗？',
      en: 'Always the same: always correct?',
    },
    subtitle: {
      zh: '把稳定、接近参考值和小刻度分开看。',
      en: 'Separate consistency, closeness and fine markings.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'accuracy',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'repeated-measurements',
    title: {
      zh: '三次不一样，哪个才算数？',
      en: 'Three different readings: which counts?',
    },
    subtitle: {
      zh: '保留证据，再让平均值讲故事。',
      en: 'Keep the evidence and let the mean tell its story.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'repeats',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'paper-thickness',
    title: {
      zh: '一张纸太薄？让一百张帮忙。',
      en: 'Too thin? Let a hundred sheets help.',
    },
    subtitle: {
      zh: '从整叠到一张，第一次间接测量。',
      en: 'From a stack to one sheet: indirect measurement.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'paper',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'position-and-reference',
    title: {
      zh: '你没走，为什么也在移动？',
      en: 'Not walking, yet moving?',
    },
    subtitle: {
      zh: '先说相对谁，再谈位置与运动。',
      en: 'Name the reference before describing motion.',
    },
    minutes: 16,
    stage: 1,
    unit: 'motion',
    kind: 'reference',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'distance-and-displacement',
    title: {
      zh: '回到原点，真的没走路吗？',
      en: 'Back at the start: no walking?',
    },
    subtitle: {
      zh: '把走过的路与位置的改变分开。',
      en: 'Separate the travelled path from a position change.',
    },
    minutes: 16,
    stage: 1,
    unit: 'motion',
    kind: 'journey',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'what-is-speed',
    title: {
      zh: '谁跑得更快？',
      en: 'Who is faster?',
    },
    subtitle: {
      zh: '用路程和时间，把“快”说清楚。',
      en: 'Describe “fast” with distance and time.',
    },
    minutes: 15,
    stage: 1,
    unit: 'motion',
    kind: 'speed',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'average-speed',
    title: {
      zh: '去得快，回来慢，平均怎么算？',
      en: 'Fast out, slow back: what is the average?',
    },
    subtitle: {
      zh: '总路程除以总时间，别忘了停留。',
      en: 'Total distance over total time, including stops.',
    },
    minutes: 17,
    stage: 1,
    unit: 'motion',
    kind: 'average',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'reading-motion-graphs',
    title: {
      zh: '线往下走，是人往地下走吗？',
      en: 'A line slopes down: walking underground?',
    },
    subtitle: {
      zh: '同一趟往返，两张图讲不同的信息。',
      en: 'Two graphs tell different parts of one trip.',
    },
    minutes: 17,
    stage: 1,
    unit: 'motion',
    kind: 'motion-graph',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'push-pull-and-shape',
    title: {
      zh: '推一下，究竟改变了什么？',
      en: 'What does a push actually change?',
    },
    subtitle: {
      zh: '小车改变运动，弹簧改变形状。',
      en: 'A cart changes motion; a spring changes shape.',
    },
    minutes: 17,
    stage: 1,
    unit: 'forces',
    kind: 'force-effects',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'balanced-and-unbalanced-forces',
    title: {
      zh: '两边都在拉，车一定停着吗？',
      en: 'Pulled equally: must the cart be still?',
    },
    subtitle: {
      zh: '同一个物体，比较所有水平力。',
      en: 'Compare horizontal forces on the same object.',
    },
    minutes: 18,
    stage: 1,
    unit: 'forces',
    kind: 'force-balance',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'friction-grip-and-slide',
    title: {
      zh: '推了却没动，摩擦在做什么？',
      en: 'Pushed but still: what is friction doing?',
    },
    subtitle: {
      zh: '从抓地到滑行，区分静摩擦与滑动摩擦。',
      en: 'From grip to sliding: static versus sliding friction.',
    },
    minutes: 18,
    stage: 1,
    unit: 'forces',
    kind: 'grip-friction',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'air-resistance-paper',
    title: {
      zh: '同一张纸，揉一下就落得更快？',
      en: 'Same paper: why does crumpling change its fall?',
    },
    subtitle: {
      zh: '保持质量相同，看形状怎样改变空气阻力。',
      en: 'Keep mass the same; investigate shape and air resistance.',
    },
    minutes: 17,
    stage: 1,
    unit: 'forces',
    kind: 'paper-drag',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'mass-versus-weight',
    title: {
      zh: '背包的1 kg，和10 N说的是一回事吗？',
      en: 'One backpack: do 1 kg and 10 N mean the same thing?',
    },
    subtitle: {
      zh: '天平比较质量，测力计测力。',
      en: 'A balance compares mass; a force meter measures force.',
    },
    minutes: 17,
    stage: 1,
    unit: 'gravity',
    kind: 'mass-weight',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'backpack-on-the-moon',
    title: {
      zh: '去月球，背包真的“变少”了吗？',
      en: 'On the Moon, does your backpack contain less?',
    },
    subtitle: {
      zh: '同一份物质，比较两处重力。',
      en: 'Same matter; compare gravity in two places.',
    },
    minutes: 18,
    stage: 1,
    unit: 'gravity',
    kind: 'moon-weight',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'heavy-light-free-fall',
    title: {
      zh: '重球的重力更大，为什么没先到？',
      en: 'More gravity on the heavy ball: why no head start?',
    },
    subtitle: {
      zh: '同高、静止释放，先移除空气这个变量。',
      en: 'Same height, released from rest: first remove air.',
    },
    minutes: 17,
    stage: 1,
    unit: 'gravity',
    kind: 'gravity-fall',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'same-volume-different-mass',
    title: {
      zh: '一样大，为什么拿起来不一样？',
      en: 'Same size: why do they feel different?',
    },
    subtitle: {
      zh: '先把大小控制住，再比较质量。',
      en: 'Keep volume fixed before comparing mass.',
    },
    minutes: 16,
    stage: 1,
    unit: 'density',
    kind: 'density-compare',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'density-mass-over-volume',
    title: {
      zh: '54 g的积木，怎样变成一个材料线索？',
      en: 'How does a 54 g block become a material clue?',
    },
    subtitle: {
      zh: '量三条边，用质量除以体积。',
      en: 'Measure three edges; divide mass by volume.',
    },
    minutes: 18,
    stage: 1,
    unit: 'density',
    kind: 'density-block',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'irregular-object-density',
    title: {
      zh: '形状不规则，材料线索还能量出来吗？',
      en: 'An irregular shape: can you still find its material clue?',
    },
    subtitle: {
      zh: '排开的水，要代表整个物体。',
      en: 'Displacement must represent the whole object.',
    },
    minutes: 18,
    stage: 1,
    unit: 'density',
    kind: 'density-displacement',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'density-floating-comparison',
    title: {
      zh: '同一块材料，换水就不沉了？',
      en: 'Same solid: new water, new outcome?',
    },
    subtitle: {
      zh: '比较物体与液体的密度。',
      en: 'Compare solid and liquid density.',
    },
    minutes: 17,
    stage: 1,
    unit: 'density',
    kind: 'density-float',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-lights-and-stores',
    title: {
      zh: '灯亮起来，电池里的能量去哪了？',
      en: 'The lamp lights up. Where does battery energy go?',
    },
    subtitle: {
      zh: '从变化找能量，从账本找去向。',
      en: 'Look for changes, then follow an energy ledger.',
    },
    minutes: 17,
    stage: 2,
    unit: 'energy',
    kind: 'energy-lamp',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'kinetic-energy-speed-squared',
    title: {
      zh: '小车速度翻倍，动能也只翻倍吗？',
      en: 'Double the cart’s speed. Only double its energy?',
    },
    subtitle: {
      zh: '保持一个量不变，比较质量与速率。',
      en: 'Hold one quantity fixed; compare mass and speed.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-kinetic',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'gravitational-energy-reference',
    title: {
      zh: '书在架子上没动，为什么也有能量线索？',
      en: 'A book rests on a shelf. Where is its energy clue?',
    },
    subtitle: {
      zh: '看物体与地球，看高度差和约定的零点。',
      en: 'Look at the object–Earth pair, height changes and the chosen zero.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-height',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'elastic-energy-release',
    title: {
      zh: '弹簧回到原长，小车为什么还在动？',
      en: 'The spring reaches its natural length. Why is the cart moving?',
    },
    subtitle: {
      zh: '形变的储备，变成运动的线索。',
      en: 'Energy associated with deformation becomes motion.',
    },
    minutes: 19,
    stage: 2,
    unit: 'energy',
    kind: 'energy-spring',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-conservation-track',
    title: {
      zh: '滑到最低处，少掉的高度变成了什么？',
      en: 'At the bottom, what has the lost height become?',
    },
    subtitle: {
      zh: '用同一份能量，读出下滑和回升。',
      en: 'Follow one energy budget downhill and back up.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-track',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-dissipation-efficiency',
    title: {
      zh: '加了粗糙垫，没回到原高的能量去哪了？',
      en: 'A rough patch lowers the return. Where did the energy go?',
    },
    subtitle: {
      zh: '守恒不等于全部有用；有用由任务决定。',
      en: 'Conserved does not mean all useful. The task decides useful.',
    },
    minutes: 19,
    stage: 2,
    unit: 'energy',
    kind: 'energy-dissipation',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'work-force-displacement',
    title: {
      zh: '提着书包很累，提力一定对它做功了吗？',
      en: 'Holding a bag is tiring. Does the lifting force do work on it?',
    },
    subtitle: {
      zh: '先指明物体、力，再看它怎样移动。',
      en: 'Name the object and force, then follow its displacement.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-direction',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'work-force-distance-area',
    title: {
      zh: '推力翻倍，还是距离加长：功怎样比较？',
      en: 'Double the force or extend the distance: how does work change?',
    },
    subtitle: {
      zh: '把力和距离的乘积，变成看得见的面积。',
      en: 'Make force times distance visible as an area.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-area',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'power-same-job-time',
    title: {
      zh: '两台升降机做同样的功，谁的功率更大？',
      en: 'Two hoists do the same work. Which has greater power?',
    },
    subtitle: {
      zh: '功回答多少，功率回答每秒多少。',
      en: 'Work asks how much; power asks how much each second.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-power',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'human-power-vertical-rise',
    title: {
      zh: '上楼的你，怎样估算机械功率？',
      en: 'How can you estimate your mechanical power on stairs?',
    },
    subtitle: {
      zh: '量竖直高度、质量和时间，不做速度排行榜。',
      en: 'Measure vertical rise, mass and time, without a race.',
    },
    minutes: 19,
    stage: 2,
    unit: 'work',
    kind: 'work-human',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-ramp-force-distance',
    title: {
      zh: '斜坡让搬货省力，也会省功吗？',
      en: 'A ramp needs less force. Does it also need less work?',
    },
    subtitle: {
      zh: '同一货物、同一高度，交换力和距离。',
      en: 'Same load and height: trade force for distance.',
    },
    minutes: 19,
    stage: 2,
    unit: 'work',
    kind: 'work-ramp',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-temperature-and-particles',
    title: {
      zh: '同样20℃，大盒气体的内能一定和小盒一样吗？',
      en: 'Both at 20°C: must a larger gas sample have the same internal energy?',
    },
    subtitle: {
      zh: '把温度、粒子运动与物质多少分开看。',
      en: 'Separate temperature, particle motion and amount of matter.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-particles',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-heating-water-mass',
    title: {
      zh: '同样的能量，为什么小杯水升温更多？',
      en: 'Same energy: why does the smaller water sample warm more?',
    },
    subtitle: {
      zh: '控制质量、输入能量与初温，把热传递写进账本。',
      en: 'Control mass, input and initial temperature; account for thermal transfer.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-heating',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-three-transfer-paths',
    title: {
      zh: '没有碰到热源，也能变暖吗？',
      en: 'Can you warm without touching the heat source?',
    },
    subtitle: {
      zh: '从勺柄、流动的水和真空间隙，分辨三条传递通路。',
      en: 'Trace a spoon, flowing water and a vacuum gap to distinguish three routes.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-paths',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-cooling-and-insulation',
    title: {
      zh: '保温杯会制造温暖，还是减慢变化？',
      en: 'Does an insulated cup create warmth or slow change?',
    },
    subtitle: {
      zh: '同样的水与初温，比较冷却曲线；再把冷水放进去。',
      en: 'Match water and initial temperature, compare curves, then try cold water.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-cups',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-evaporation-and-cooling',
    title: {
      zh: '水没有沸腾，湿布为什么也会变凉？',
      en: 'Without boiling, why can a wet cloth cool?',
    },
    subtitle: {
      zh: '追踪表面蒸发、剩余水量与能量去向。',
      en: 'Follow surface evaporation, remaining water and energy destinations.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-wet',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-ice-melts-and-freezes',
    title: {
      zh: '冰在融化，温度怎么没升？',
      en: 'The ice is melting. Why is its temperature not rising?',
    },
    subtitle: {
      zh: '在0℃观察熔化与凝固，追踪能量和状态。',
      en: 'Follow energy and state during melting and freezing at 0°C.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-fusion',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-boiling-not-hotter',
    title: {
      zh: '水已经沸腾，再供热会发生什么？',
      en: 'The water is boiling. What does more heating change?',
    },
    subtitle: {
      zh: '看液体质量和气泡，把沸腾与蒸发区分开。',
      en: 'Inspect liquid mass and bubbles; distinguish boiling from evaporation.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-boiling',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-drops-outside-cold-cup',
    title: {
      zh: '杯子没漏，外壁水珠从哪里来？',
      en: 'The cup is not leaking. Where do outside droplets come from?',
    },
    subtitle: {
      zh: '比较杯壁与空气，让看不见的水蒸气留下线索。',
      en: 'Compare surface and air; find evidence of invisible water vapour.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-condensation',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-read-a-heating-curve',
    title: {
      zh: '加热曲线的平段，能量暂停了吗？',
      en: 'Does a flat heating curve mean energy input has paused?',
    },
    subtitle: {
      zh: '从−10℃冰到20℃水，把温度、状态与功率连起来。',
      en: 'Link temperature, state and power from −10°C ice to 20°C water.',
    },
    minutes: 20,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-curve',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'sound-vibrating-source',
    title: {
      zh: '橡皮筋出声时，它在做什么？',
      en: 'What is a rubber band doing when it sounds?',
    },
    subtitle: {
      zh: '从来回运动找到声源，再追踪一小段信号。',
      en: 'Find the vibrating source, then follow a brief signal.',
    },
    minutes: 17,
    stage: 2,
    unit: 'sound',
    kind: 'sound-source',
    pack: 'sound',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'sound-medium-local-motion',
    title: {
      zh: '声音到了耳边，空气也一路跑来了吗？',
      en: 'Sound reaches your ear. Did the air travel all the way?',
    },
    subtitle: {
      zh: '追踪一个有颜色的标记，比较空气、水与真空。',
      en: 'Track a coloured marker in air, water and vacuum.',
    },
    minutes: 19,
    stage: 2,
    unit: 'sound',
    kind: 'sound-medium',
    pack: 'sound',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'sound-frequency-and-pitch',
    title: {
      zh: '同样轻的两个音，为什么一个更尖？',
      en: 'Two gentle tones. Why is one higher?',
    },
    subtitle: {
      zh: '在相同时间里数振动次数，调整频率并试听。',
      en: 'Count cycles over equal time, adjust frequency and listen.',
    },
    minutes: 18,
    stage: 2,
    unit: 'sound',
    kind: 'sound-pitch',
    pack: 'sound',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'sound-amplitude-and-loudness',
    title: {
      zh: '同一个音，怎样变得更明显？',
      en: 'How can the same tone become more noticeable?',
    },
    subtitle: {
      zh: '固定频率，只改振幅；把音调和响度分开。',
      en: 'Keep frequency fixed and change amplitude; separate pitch and loudness.',
    },
    minutes: 18,
    stage: 2,
    unit: 'sound',
    kind: 'sound-amplitude',
    pack: 'sound',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'sound-echo-distance-ultrasound',
    title: {
      zh: '回来的声音，怎样告诉我们距离？',
      en: 'How can a returning sound tell us distance?',
    },
    subtitle: {
      zh: '追踪往返路径，比较远近与超声脉冲。',
      en: 'Follow the round trip; compare distance and an ultrasonic pulse.',
    },
    minutes: 20,
    stage: 2,
    unit: 'sound',
    kind: 'sound-ranging',
    pack: 'sound',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'light-rays-and-shadows',
    title: {
      zh: '手没变大，影子为什么变大？',
      en: 'Same hand. Why a bigger shadow?',
    },
    subtitle: {
      zh: '用两条边界光线，预测屏幕上的影子。',
      en: 'Predict a shadow using two boundary rays.',
    },
    minutes: 18,
    stage: 2,
    unit: 'light',
    kind: 'light-shadow',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'light-reflection-from-normal',
    title: {
      zh: '把光“转弯”，该瞄准哪里？',
      en: 'Where do you aim to turn a light ray?',
    },
    subtitle: {
      zh: '先画法线，再让两侧的角度说话。',
      en: 'Draw a normal, then compare the angles.',
    },
    minutes: 17,
    stage: 2,
    unit: 'light',
    kind: 'light-reflection',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'light-plane-mirror-image',
    title: {
      zh: '镜子后面，真的有另一个你？',
      en: 'Is there really another you behind the mirror?',
    },
    subtitle: {
      zh: '追踪反射，再把方向向后延长。',
      en: 'Follow reflection, then extend directions backward.',
    },
    minutes: 18,
    stage: 2,
    unit: 'light',
    kind: 'light-mirror',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'light-water-refraction',
    title: {
      zh: '水里的吸管，在哪里“折断”了？',
      en: 'Where did the straw in water “break”?',
    },
    subtitle: {
      zh: '改变介质，看光的方向如何改变。',
      en: 'Change the medium and follow the direction.',
    },
    minutes: 20,
    stage: 2,
    unit: 'light',
    kind: 'light-refraction',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'light-lens-real-and-virtual',
    title: {
      zh: '放大镜，为什么有时放大、有时倒过来？',
      en: 'Why does a magnifier sometimes enlarge and sometimes invert?',
    },
    subtitle: {
      zh: '沿两条主光线，分清能接到屏幕的像。',
      en: 'Use two principal rays to find images a screen can collect.',
    },
    minutes: 20,
    stage: 2,
    unit: 'light',
    kind: 'light-lens',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'light-colour-white-and-rainbow',
    title: {
      zh: '彩虹的颜色，原本藏在哪里？',
      en: 'Where were the rainbow colours hiding?',
    },
    subtitle: {
      zh: '用棱镜分开已有的光，再试一个滤光片。',
      en: 'Separate existing light with a prism, then try a filter.',
    },
    minutes: 20,
    stage: 2,
    unit: 'light',
    kind: 'light-colour',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'light-eye-focus-on-retina',
    title: {
      zh: '从远处看回书本，眼睛调了哪里？',
      en: 'Look from far away back to a book. What adjusts?',
    },
    subtitle: {
      zh: '视网膜不搬家，改变会聚能力来对焦。',
      en: 'Keep the retina fixed and change focusing strength.',
    },
    minutes: 19,
    stage: 2,
    unit: 'light',
    kind: 'light-eye',
    pack: 'light',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'pressure-force-over-area',
    title: {
      zh: '同一个书包，为什么宽带更舒服？',
      en: 'Same backpack. Why might a wider strap help?',
    },
    subtitle: {
      zh: '先把力分给小方格，再认识压强。',
      en: 'Share the force across little squares, then meet pressure.',
    },
    minutes: 17,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-contact',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'pressure-shoes-contact',
    title: {
      zh: '雪鞋为什么做得那么大？',
      en: 'Why are snowshoes so large?',
    },
    subtitle: {
      zh: '站着不动的人，同样重量，三种接触面积。',
      en: 'Same stationary person and load. Three contact areas.',
    },
    minutes: 16,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-shoes',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'pressure-liquid-depth',
    title: {
      zh: '水瓶低处的小孔，为什么更有劲？',
      en: 'Why does a lower bottle hole have more push?',
    },
    subtitle: {
      zh: '从水面量深度，再转动同一点的小探头。',
      en: 'Measure depth from the surface, then turn a tiny probe at one point.',
    },
    minutes: 19,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-liquid',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'pressure-atmosphere-difference',
    title: {
      zh: '看不见的空气，为什么能推？',
      en: 'How can invisible air push?',
    },
    subtitle: {
      zh: '同时看外面与里面，不把“吸住”当作新力量。',
      en: 'Look outside and inside together; “suction” is not an extra force.',
    },
    minutes: 18,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-air',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'pressure-drinking-straw',
    title: {
      zh: '吸管里，是谁把水送上来？',
      en: 'Who pushes water up a straw?',
    },
    subtitle: {
      zh: '嘴让管口压强降低，杯面上的空气还在推。',
      en: 'Lower pressure at the top; air still pushes on the cup surface.',
    },
    minutes: 18,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-straw',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'pressure-syringe-trapped-air',
    title: {
      zh: '封住管口，活塞为什么更难推？',
      en: 'Why is a sealed syringe harder to push?',
    },
    subtitle: {
      zh: '一小团空气没走，体积变了，压力怎样变？',
      en: 'The trapped air stays. How does its pressure change with volume?',
    },
    minutes: 19,
    stage: 3,
    unit: 'pressure',
    kind: 'pressure-syringe',
    pack: 'pressure',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-more-than-floating',
    title: {
      zh: '有浮力，为什么还会下沉？',
      en: 'With buoyancy, why can an object still sink?',
    },
    subtitle: {
      zh: '把水的托力、物体重量与合力分开。',
      en: 'Separate water’s support, weight and net force.',
    },
    minutes: 17,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-release',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'buoyancy-pressure-from-below',
    title: {
      zh: '水为什么从下面托得更多？',
      en: 'Why does water push more from below?',
    },
    subtitle: {
      zh: '把上一单元的压强差，变成一个向上的力。',
      en: 'Turn a pressure difference into an upward force.',
    },
    minutes: 19,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-pressure',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-displaced-water',
    title: {
      zh: '水位升高，究竟量到哪一部分？',
      en: 'Which part does a rising water level measure?',
    },
    subtitle: {
      zh: '同一个物体，露在水外的部分不算排水。',
      en: 'The part above water does not displace water.',
    },
    minutes: 17,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-displacement',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-weight-of-displaced-fluid',
    title: {
      zh: '排开的水，能告诉我们托力吗？',
      en: 'Can displaced water tell us the supporting force?',
    },
    subtitle: {
      zh: '一杯排开的水，连接体积、质量与重量。',
      en: 'Connect displaced volume, mass and weight.',
    },
    minutes: 20,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-archimedes',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-sealed-hull-and-cargo',
    title: {
      zh: '同样300 g，为什么盒形船体能浮？',
      en: 'Same 300 g: why can a box-shaped hull float?',
    },
    subtitle: {
      zh: '增加能排水的体积，再看载荷怎样改变吃水。',
      en: 'Increase water-excluding volume, then follow cargo and draft.',
    },
    minutes: 19,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-ship',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-submarine-ballast',
    title: {
      zh: '潜水艇不变大，怎样上浮或下潜？',
      en: 'How can a submarine rise or dive without growing?',
    },
    subtitle: {
      zh: '外部体积不变，改变压载水的质量。',
      en: 'Keep external volume fixed and change ballast-water mass.',
    },
    minutes: 18,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-submarine',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'buoyancy-hot-air-balloon',
    title: {
      zh: '空气也能托起一个气球吗？',
      en: 'Can air support a balloon too?',
    },
    subtitle: {
      zh: '别漏算气球里的空气，也别漏算吊篮与载荷。',
      en: 'Count enclosed air as well as equipment and payload.',
    },
    minutes: 20,
    stage: 3,
    unit: 'buoyancy',
    kind: 'buoyancy-balloon',
    pack: 'buoyancy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-longer-handle',
    title: {
      zh: '同一个盒子，长把手为什么更省力？',
      en: 'Same box: why does a longer handle need less force?',
    },
    subtitle: {
      zh: '找支点、看两边，让一根杆成为搬运助手。',
      en: 'Find the pivot and compare the two sides of a lifting bar.',
    },
    minutes: 18,
    stage: 3,
    unit: 'machines',
    kind: 'machine-lever',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'machines-turning-direction',
    title: {
      zh: '同样的力，为什么沿把手拉不动转轴？',
      en: 'Same force: why does pulling along a handle give no turning effect?',
    },
    subtitle: {
      zh: '从门把手和扳手，找到真正的力臂。',
      en: 'Find the true moment arm in a door handle or wrench.',
    },
    minutes: 19,
    stage: 3,
    unit: 'machines',
    kind: 'machine-turning',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-rope-and-pulleys',
    title: {
      zh: '多一个滑轮，就一定省一半力吗？',
      en: 'Does adding a pulley always halve the force?',
    },
    subtitle: {
      zh: '数托住活动部分的绳段，而不是数轮子。',
      en: 'Count rope strands supporting the moving assembly, not wheels.',
    },
    minutes: 20,
    stage: 3,
    unit: 'machines',
    kind: 'machine-pulley',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-gears-trade-speed',
    title: {
      zh: '小齿轮带大齿轮，快慢与转动作用怎样交换？',
      en: 'Small gear drives big gear: how do speed and torque trade?',
    },
    subtitle: {
      zh: '同一处咬合，数齿、数圈、看方向。',
      en: 'At one mesh, count teeth and turns and watch direction.',
    },
    minutes: 20,
    stage: 3,
    unit: 'machines',
    kind: 'machine-gears',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-force-distance-bargain',
    title: {
      zh: '省了四分之三的力，为什么没有省功？',
      en: 'Why does saving three quarters of the force not save work?',
    },
    subtitle: {
      zh: '把力和距离写进同一张账本。',
      en: 'Put force and distance in the same ledger.',
    },
    minutes: 19,
    stage: 3,
    unit: 'machines',
    kind: 'machine-advantage',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'machines-friction-energy-ledger',
    title: {
      zh: '真实滑轮，为什么比理想模型更费力？',
      en: 'Why does a real pulley need more effort than the ideal model?',
    },
    subtitle: {
      zh: '把摩擦、输入功与有用输出放进同一本账。',
      en: 'Include friction, input work and useful output in one ledger.',
    },
    minutes: 20,
    stage: 3,
    unit: 'machines',
    kind: 'machine-real',
    pack: 'machines',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-charge-transfer',
    title: {
      zh: '衣服粘在一起，电荷是新造出来的吗？',
      en: 'Clinging clothes: was new charge created?',
    },
    subtitle: {
      zh: '追踪一小部分电子，给两个物体一起记账。',
      en: 'Follow a few electrons and account for both objects.',
    },
    minutes: 16,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-charge',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'electric-attract-repel-neutral',
    title: {
      zh: '吸过来，就一定带相反电荷吗？',
      en: 'Attraction: must the charges be opposite?',
    },
    subtitle: {
      zh: '同号、异号与中性物体，三种情况分开看。',
      en: 'Distinguish like signs, unlike signs and a neutral object.',
    },
    minutes: 16,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-interaction',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-current-counts-charge',
    title: {
      zh: '同样的电荷，慢慢通过和快速通过一样吗？',
      en: 'Same charge: does passing slowly or quickly matter?',
    },
    subtitle: {
      zh: '在导线的一处数电荷，把“多少”和“多快”分开。',
      en: 'Count charge at one wire section: how much versus how quickly.',
    },
    minutes: 18,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-current',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'electric-complete-loop',
    title: {
      zh: '灯泡接到电池，为什么还不亮？',
      en: 'Connected to a battery: why is the lamp still off?',
    },
    subtitle: {
      zh: '别只找一根线，沿整个回路走一圈。',
      en: 'Trace the whole loop, not just one wire.',
    },
    minutes: 16,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-circuit',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-battery-energy-push',
    title: {
      zh: '电池换个方向，电荷还是原来的那些吗？',
      en: 'Reverse a cell: are the charges still there?',
    },
    subtitle: {
      zh: '电池改变驱动方向和能量转移，不制造导线里的电荷。',
      en: 'A cell changes driving direction and energy transfer, not the wire’s charge supply.',
    },
    minutes: 18,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-battery',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'electric-lamp-keeps-charge',
    title: {
      zh: '灯泡吃掉的是电流，还是转移能量？',
      en: 'Does a lamp eat current, or transfer energy?',
    },
    subtitle: {
      zh: '进出电荷相同，光与热的账本可以不同。',
      en: 'Equal charge in and out; different light and heat accounts.',
    },
    minutes: 18,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-lamp',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-switch-breaks-loop',
    title: {
      zh: '开关在灯前或灯后，真的有区别吗？',
      en: 'A switch before or after the lamp: does it matter?',
    },
    subtitle: {
      zh: '一个小缺口，改变的是整个闭合路径。',
      en: 'One small gap changes the whole closed path.',
    },
    minutes: 15,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-switch',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-material-and-contact',
    title: {
      zh: '有一根“桥”，为什么电流还是过不去？',
      en: 'A bridge is there: why can current still not pass?',
    },
    subtitle: {
      zh: '材料能不能导电，接触有没有连好，分别检查。',
      en: 'Check material conduction and contact separately.',
    },
    minutes: 17,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-materials',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'electric-series-one-path',
    title: {
      zh: '两盏灯排成一条路，谁拿走了电流？',
      en: 'Two lamps in one path: who takes the current?',
    },
    subtitle: {
      zh: '串联只有一条通路，电流相同，能量按元件分配。',
      en: 'Series has one path: same current, energy shared by the loads.',
    },
    minutes: 19,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-series',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'electric-parallel-branch-choice',
    title: {
      zh: '关掉一盏灯，另一盏为什么还亮？',
      en: 'Switch one lamp off: why can the other stay on?',
    },
    subtitle: {
      zh: '沿分叉追踪电流，先找共同的两个节点。',
      en: 'Follow currents through a fork and find the two shared nodes.',
    },
    minutes: 20,
    stage: 3,
    unit: 'electricity',
    kind: 'electric-parallel',
    pack: 'electricity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
];
