// Generated by scripts/update-catalog.mjs. Edit lesson content, then regenerate.
import type { LessonCatalogEntry } from './catalogEntry';
export const lessonCatalog: LessonCatalogEntry[] = [
  {
    id: 'physics-everywhere',
    title: {
      zh: '物理无处不在',
      en: 'Physics is everywhere',
    },
    subtitle: {
      zh: '从一颗滚动的球，发现世界的规律。',
      en: 'Discover a pattern in a rolling ball.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'friction',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 2,
      },
    ],
  },
  {
    id: 'ask-a-physicist',
    title: {
      zh: '像物理学家一样提问',
      en: 'Ask like a physicist',
    },
    subtitle: {
      zh: '好问题，是一场实验的开始。',
      en: 'A good question starts an experiment.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'variables',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'observe-explain',
    title: {
      zh: '观察，还是解释？',
      en: 'Observation or explanation?',
    },
    subtitle: {
      zh: '先说发生了什么，再追问为什么。',
      en: 'Describe what happened, then ask why.',
    },
    minutes: 12,
    stage: 0,
    unit: 'curiosity',
    kind: 'observation',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'what-can-we-measure',
    title: {
      zh: '“太重了”有多重？',
      en: 'How heavy is “too heavy”?',
    },
    subtitle: {
      zh: '给书包、歌曲和铅笔找一个测量办法。',
      en: 'Find ways to measure a bag, a song and a pencil.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'quantities',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
    ],
  },
  {
    id: 'units-make-sense',
    title: {
      zh: '数字换了，绳子变了吗？',
      en: 'Different numbers, same string?',
    },
    subtitle: {
      zh: '24 cm、240 mm 和 0.24 m 的秘密。',
      en: 'The secret of 24 cm, 240 mm and 0.24 m.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'units',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-length',
    title: {
      zh: '给世界一把尺',
      en: 'A ruler for the world',
    },
    subtitle: {
      zh: '从“差不多”，走向有单位的测量。',
      en: 'From “about this much” to a measurement.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'length',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-time',
    title: {
      zh: '一秒很短，怎么量准？',
      en: 'How can we time a tiny interval?',
    },
    subtitle: {
      zh: '数十次摆动，比只数一次更可靠。',
      en: 'Time ten swings instead of just one.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'time',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-mass',
    title: {
      zh: '大块海绵比小块金属重吗？',
      en: 'Is a big sponge heavier than small metal?',
    },
    subtitle: {
      zh: '让天平来判断，别只看大小。',
      en: 'Let a balance decide, not size alone.',
    },
    minutes: 15,
    stage: 0,
    unit: 'measurement',
    kind: 'mass',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'measure-temperature',
    title: {
      zh: '感觉冷，就真的更冷吗？',
      en: 'Does feeling colder mean being colder?',
    },
    subtitle: {
      zh: '木头与金属，藏着一个温度谜题。',
      en: 'Wood and metal hide a temperature mystery.',
    },
    minutes: 12,
    stage: 0,
    unit: 'measurement',
    kind: 'temperature',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'tables-and-data',
    title: {
      zh: '把发现装进一张表。',
      en: 'Put discoveries into a table.',
    },
    subtitle: {
      zh: '一次结果可能偶然，几次记录才能比较。',
      en: 'Compare repeated records, not one lucky result.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'data',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'simple-graphs',
    title: {
      zh: '一条线，讲一个走路故事。',
      en: 'A line tells a walking story.',
    },
    subtitle: {
      zh: '不是地图，而是时间与路程的关系。',
      en: 'A relationship between time and distance, not a map.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'graph',
    pack: 'measurement',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'cause-and-effect',
    title: {
      zh: '改了两件事，能找到原因吗？',
      en: 'Two changes: can we identify the cause?',
    },
    subtitle: {
      zh: '把“同时发生”变成值得相信的比较。',
      en: 'Turn “happened together” into a fair comparison.',
    },
    minutes: 15,
    stage: 0,
    unit: 'patterns',
    kind: 'fair-test',
    pack: 'discoveries',
    predictionCount: 2,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-ice-floats',
    title: {
      zh: '冰山藏起了多少？',
      en: 'How much of an iceberg is hidden?',
    },
    subtitle: {
      zh: '水面上的小尖尖，不是冰山的全部。',
      en: 'The visible tip is only part of the story.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'floating',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-ships-float',
    title: {
      zh: '同一团泥，能变成船吗？',
      en: 'Can the same clay become a boat?',
    },
    subtitle: {
      zh: '质量没变，形状却改变了能排开的水。',
      en: 'Same mass, different water displacement.',
    },
    minutes: 18,
    stage: 0,
    unit: 'mysteries',
    kind: 'boats',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-balls-bounce',
    title: {
      zh: '球怎么又回来了？',
      en: 'How does the ball come back up?',
    },
    subtitle: {
      zh: '落下、变形、回弹，能量走了一条什么路？',
      en: 'Fall, deform, rebound: follow the energy.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'bounce',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-echoes-return',
    title: {
      zh: '声音走了多远才回来？',
      en: 'How far does an echo travel?',
    },
    subtitle: {
      zh: '一声呼喊，藏着一趟往返旅行。',
      en: 'One call makes a return journey.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'echo',
    pack: 'mysteries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 2,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'why-mirrors-show-us',
    title: {
      zh: '镜子后面真有另一个你吗？',
      en: 'Is another you really behind the mirror?',
    },
    subtitle: {
      zh: '跟随真正的光，看懂“像”的位置。',
      en: 'Follow real light to locate the image.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'mirror',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-balloons-attract',
    title: {
      zh: '墙没带电，气球怎么还靠过来？',
      en: 'Why does a balloon approach a neutral wall?',
    },
    subtitle: {
      zh: '不接触，也能有作用；中性也不是没有电荷。',
      en: 'An interaction without contact; neutral is not charge-free.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'static',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'why-seatbelts-matter',
    title: {
      zh: '车停了，身体为什么还想向前？',
      en: 'Why does your body keep moving when the car stops?',
    },
    subtitle: {
      zh: '用玩具模型认识惯性与减速作用。',
      en: 'Explore inertia and slowing with a toy model.',
    },
    minutes: 15,
    stage: 0,
    unit: 'mysteries',
    kind: 'seatbelt',
    pack: 'discoveries',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'measure-volume',
    title: {
      zh: '石头没有直边，怎么量大小？',
      en: 'No straight edges: how big is the stone?',
    },
    subtitle: {
      zh: '让水帮你量出占据的空间。',
      en: 'Let water reveal the space it occupies.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'volume',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'accuracy-and-resolution',
    title: {
      zh: '每次都一样，就一定量对了吗？',
      en: 'Always the same: always correct?',
    },
    subtitle: {
      zh: '把稳定、接近参考值和小刻度分开看。',
      en: 'Separate consistency, closeness and fine markings.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'accuracy',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'repeated-measurements',
    title: {
      zh: '三次不一样，哪个才算数？',
      en: 'Three different readings: which counts?',
    },
    subtitle: {
      zh: '保留证据，再让平均值讲故事。',
      en: 'Keep the evidence and let the mean tell its story.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'repeats',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'paper-thickness',
    title: {
      zh: '一张纸太薄？让一百张帮忙。',
      en: 'Too thin? Let a hundred sheets help.',
    },
    subtitle: {
      zh: '从整叠到一张，第一次间接测量。',
      en: 'From a stack to one sheet: indirect measurement.',
    },
    minutes: 16,
    stage: 1,
    unit: 'measurement',
    kind: 'paper',
    pack: 'measurementSkills',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'position-and-reference',
    title: {
      zh: '你没走，为什么也在移动？',
      en: 'Not walking, yet moving?',
    },
    subtitle: {
      zh: '先说相对谁，再谈位置与运动。',
      en: 'Name the reference before describing motion.',
    },
    minutes: 16,
    stage: 1,
    unit: 'motion',
    kind: 'reference',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'distance-and-displacement',
    title: {
      zh: '回到原点，真的没走路吗？',
      en: 'Back at the start: no walking?',
    },
    subtitle: {
      zh: '把走过的路与位置的改变分开。',
      en: 'Separate the travelled path from a position change.',
    },
    minutes: 16,
    stage: 1,
    unit: 'motion',
    kind: 'journey',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'what-is-speed',
    title: {
      zh: '谁跑得更快？',
      en: 'Who is faster?',
    },
    subtitle: {
      zh: '用路程和时间，把“快”说清楚。',
      en: 'Describe “fast” with distance and time.',
    },
    minutes: 15,
    stage: 1,
    unit: 'motion',
    kind: 'speed',
    pack: 'foundations',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'average-speed',
    title: {
      zh: '去得快，回来慢，平均怎么算？',
      en: 'Fast out, slow back: what is the average?',
    },
    subtitle: {
      zh: '总路程除以总时间，别忘了停留。',
      en: 'Total distance over total time, including stops.',
    },
    minutes: 17,
    stage: 1,
    unit: 'motion',
    kind: 'average',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'reading-motion-graphs',
    title: {
      zh: '线往下走，是人往地下走吗？',
      en: 'A line slopes down: walking underground?',
    },
    subtitle: {
      zh: '同一趟往返，两张图讲不同的信息。',
      en: 'Two graphs tell different parts of one trip.',
    },
    minutes: 17,
    stage: 1,
    unit: 'motion',
    kind: 'motion-graph',
    pack: 'motion',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'push-pull-and-shape',
    title: {
      zh: '推一下，究竟改变了什么？',
      en: 'What does a push actually change?',
    },
    subtitle: {
      zh: '小车改变运动，弹簧改变形状。',
      en: 'A cart changes motion; a spring changes shape.',
    },
    minutes: 17,
    stage: 1,
    unit: 'forces',
    kind: 'force-effects',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'balanced-and-unbalanced-forces',
    title: {
      zh: '两边都在拉，车一定停着吗？',
      en: 'Pulled equally: must the cart be still?',
    },
    subtitle: {
      zh: '同一个物体，比较所有水平力。',
      en: 'Compare horizontal forces on the same object.',
    },
    minutes: 18,
    stage: 1,
    unit: 'forces',
    kind: 'force-balance',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'friction-grip-and-slide',
    title: {
      zh: '推了却没动，摩擦在做什么？',
      en: 'Pushed but still: what is friction doing?',
    },
    subtitle: {
      zh: '从抓地到滑行，区分静摩擦与滑动摩擦。',
      en: 'From grip to sliding: static versus sliding friction.',
    },
    minutes: 18,
    stage: 1,
    unit: 'forces',
    kind: 'grip-friction',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
    ],
  },
  {
    id: 'air-resistance-paper',
    title: {
      zh: '同一张纸，揉一下就落得更快？',
      en: 'Same paper: why does crumpling change its fall?',
    },
    subtitle: {
      zh: '保持质量相同，看形状怎样改变空气阻力。',
      en: 'Keep mass the same; investigate shape and air resistance.',
    },
    minutes: 17,
    stage: 1,
    unit: 'forces',
    kind: 'paper-drag',
    pack: 'forces',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'mass-versus-weight',
    title: {
      zh: '背包的1 kg，和10 N说的是一回事吗？',
      en: 'One backpack: do 1 kg and 10 N mean the same thing?',
    },
    subtitle: {
      zh: '天平比较质量，测力计测力。',
      en: 'A balance compares mass; a force meter measures force.',
    },
    minutes: 17,
    stage: 1,
    unit: 'gravity',
    kind: 'mass-weight',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'backpack-on-the-moon',
    title: {
      zh: '去月球，背包真的“变少”了吗？',
      en: 'On the Moon, does your backpack contain less?',
    },
    subtitle: {
      zh: '同一份物质，比较两处重力。',
      en: 'Same matter; compare gravity in two places.',
    },
    minutes: 18,
    stage: 1,
    unit: 'gravity',
    kind: 'moon-weight',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'heavy-light-free-fall',
    title: {
      zh: '重球的重力更大，为什么没先到？',
      en: 'More gravity on the heavy ball: why no head start?',
    },
    subtitle: {
      zh: '同高、静止释放，先移除空气这个变量。',
      en: 'Same height, released from rest: first remove air.',
    },
    minutes: 17,
    stage: 1,
    unit: 'gravity',
    kind: 'gravity-fall',
    pack: 'gravity',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'same-volume-different-mass',
    title: {
      zh: '一样大，为什么拿起来不一样？',
      en: 'Same size: why do they feel different?',
    },
    subtitle: {
      zh: '先把大小控制住，再比较质量。',
      en: 'Keep volume fixed before comparing mass.',
    },
    minutes: 16,
    stage: 1,
    unit: 'density',
    kind: 'density-compare',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'density-mass-over-volume',
    title: {
      zh: '54 g的积木，怎样变成一个材料线索？',
      en: 'How does a 54 g block become a material clue?',
    },
    subtitle: {
      zh: '量三条边，用质量除以体积。',
      en: 'Measure three edges; divide mass by volume.',
    },
    minutes: 18,
    stage: 1,
    unit: 'density',
    kind: 'density-block',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'irregular-object-density',
    title: {
      zh: '形状不规则，材料线索还能量出来吗？',
      en: 'An irregular shape: can you still find its material clue?',
    },
    subtitle: {
      zh: '排开的水，要代表整个物体。',
      en: 'Displacement must represent the whole object.',
    },
    minutes: 18,
    stage: 1,
    unit: 'density',
    kind: 'density-displacement',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'density-floating-comparison',
    title: {
      zh: '同一块材料，换水就不沉了？',
      en: 'Same solid: new water, new outcome?',
    },
    subtitle: {
      zh: '比较物体与液体的密度。',
      en: 'Compare solid and liquid density.',
    },
    minutes: 17,
    stage: 1,
    unit: 'density',
    kind: 'density-float',
    pack: 'density',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-lights-and-stores',
    title: {
      zh: '灯亮起来，电池里的能量去哪了？',
      en: 'The lamp lights up. Where does battery energy go?',
    },
    subtitle: {
      zh: '从变化找能量，从账本找去向。',
      en: 'Look for changes, then follow an energy ledger.',
    },
    minutes: 17,
    stage: 2,
    unit: 'energy',
    kind: 'energy-lamp',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'kinetic-energy-speed-squared',
    title: {
      zh: '小车速度翻倍，动能也只翻倍吗？',
      en: 'Double the cart’s speed. Only double its energy?',
    },
    subtitle: {
      zh: '保持一个量不变，比较质量与速率。',
      en: 'Hold one quantity fixed; compare mass and speed.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-kinetic',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'gravitational-energy-reference',
    title: {
      zh: '书在架子上没动，为什么也有能量线索？',
      en: 'A book rests on a shelf. Where is its energy clue?',
    },
    subtitle: {
      zh: '看物体与地球，看高度差和约定的零点。',
      en: 'Look at the object–Earth pair, height changes and the chosen zero.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-height',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'elastic-energy-release',
    title: {
      zh: '弹簧回到原长，小车为什么还在动？',
      en: 'The spring reaches its natural length. Why is the cart moving?',
    },
    subtitle: {
      zh: '形变的储备，变成运动的线索。',
      en: 'Energy associated with deformation becomes motion.',
    },
    minutes: 19,
    stage: 2,
    unit: 'energy',
    kind: 'energy-spring',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-conservation-track',
    title: {
      zh: '滑到最低处，少掉的高度变成了什么？',
      en: 'At the bottom, what has the lost height become?',
    },
    subtitle: {
      zh: '用同一份能量，读出下滑和回升。',
      en: 'Follow one energy budget downhill and back up.',
    },
    minutes: 18,
    stage: 2,
    unit: 'energy',
    kind: 'energy-track',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'energy-dissipation-efficiency',
    title: {
      zh: '加了粗糙垫，没回到原高的能量去哪了？',
      en: 'A rough patch lowers the return. Where did the energy go?',
    },
    subtitle: {
      zh: '守恒不等于全部有用；有用由任务决定。',
      en: 'Conserved does not mean all useful. The task decides useful.',
    },
    minutes: 19,
    stage: 2,
    unit: 'energy',
    kind: 'energy-dissipation',
    pack: 'energy',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'work-force-displacement',
    title: {
      zh: '提着书包很累，提力一定对它做功了吗？',
      en: 'Holding a bag is tiring. Does the lifting force do work on it?',
    },
    subtitle: {
      zh: '先指明物体、力，再看它怎样移动。',
      en: 'Name the object and force, then follow its displacement.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-direction',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'work-force-distance-area',
    title: {
      zh: '推力翻倍，还是距离加长：功怎样比较？',
      en: 'Double the force or extend the distance: how does work change?',
    },
    subtitle: {
      zh: '把力和距离的乘积，变成看得见的面积。',
      en: 'Make force times distance visible as an area.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-area',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
    ],
  },
  {
    id: 'power-same-job-time',
    title: {
      zh: '两台升降机做同样的功，谁的功率更大？',
      en: 'Two hoists do the same work. Which has greater power?',
    },
    subtitle: {
      zh: '功回答多少，功率回答每秒多少。',
      en: 'Work asks how much; power asks how much each second.',
    },
    minutes: 18,
    stage: 2,
    unit: 'work',
    kind: 'work-power',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'human-power-vertical-rise',
    title: {
      zh: '上楼的你，怎样估算机械功率？',
      en: 'How can you estimate your mechanical power on stairs?',
    },
    subtitle: {
      zh: '量竖直高度、质量和时间，不做速度排行榜。',
      en: 'Measure vertical rise, mass and time, without a race.',
    },
    minutes: 19,
    stage: 2,
    unit: 'work',
    kind: 'work-human',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 3,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'machines-ramp-force-distance',
    title: {
      zh: '斜坡让搬货省力，也会省功吗？',
      en: 'A ramp needs less force. Does it also need less work?',
    },
    subtitle: {
      zh: '同一货物、同一高度，交换力和距离。',
      en: 'Same load and height: trade force for distance.',
    },
    minutes: 19,
    stage: 2,
    unit: 'work',
    kind: 'work-ramp',
    pack: 'work',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 3,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-temperature-and-particles',
    title: {
      zh: '同样20℃，大盒气体的内能一定和小盒一样吗？',
      en: 'Both at 20°C: must a larger gas sample have the same internal energy?',
    },
    subtitle: {
      zh: '把温度、粒子运动与物质多少分开看。',
      en: 'Separate temperature, particle motion and amount of matter.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-particles',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-heating-water-mass',
    title: {
      zh: '同样的能量，为什么小杯水升温更多？',
      en: 'Same energy: why does the smaller water sample warm more?',
    },
    subtitle: {
      zh: '控制质量、输入能量与初温，把热传递写进账本。',
      en: 'Control mass, input and initial temperature; account for thermal transfer.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-heating',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-three-transfer-paths',
    title: {
      zh: '没有碰到热源，也能变暖吗？',
      en: 'Can you warm without touching the heat source?',
    },
    subtitle: {
      zh: '从勺柄、流动的水和真空间隙，分辨三条传递通路。',
      en: 'Trace a spoon, flowing water and a vacuum gap to distinguish three routes.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-paths',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-cooling-and-insulation',
    title: {
      zh: '保温杯会制造温暖，还是减慢变化？',
      en: 'Does an insulated cup create warmth or slow change?',
    },
    subtitle: {
      zh: '同样的水与初温，比较冷却曲线；再把冷水放进去。',
      en: 'Match water and initial temperature, compare curves, then try cold water.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-cups',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'thermal-evaporation-and-cooling',
    title: {
      zh: '水没有沸腾，湿布为什么也会变凉？',
      en: 'Without boiling, why can a wet cloth cool?',
    },
    subtitle: {
      zh: '追踪表面蒸发、剩余水量与能量去向。',
      en: 'Follow surface evaporation, remaining water and energy destinations.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'thermal-wet',
    pack: 'thermal',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-ice-melts-and-freezes',
    title: {
      zh: '冰在融化，温度怎么没升？',
      en: 'The ice is melting. Why is its temperature not rising?',
    },
    subtitle: {
      zh: '在0℃观察熔化与凝固，追踪能量和状态。',
      en: 'Follow energy and state during melting and freezing at 0°C.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-fusion',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-boiling-not-hotter',
    title: {
      zh: '水已经沸腾，再供热会发生什么？',
      en: 'The water is boiling. What does more heating change?',
    },
    subtitle: {
      zh: '看液体质量和气泡，把沸腾与蒸发区分开。',
      en: 'Inspect liquid mass and bubbles; distinguish boiling from evaporation.',
    },
    minutes: 19,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-boiling',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-drops-outside-cold-cup',
    title: {
      zh: '杯子没漏，外壁水珠从哪里来？',
      en: 'The cup is not leaking. Where do outside droplets come from?',
    },
    subtitle: {
      zh: '比较杯壁与空气，让看不见的水蒸气留下线索。',
      en: 'Compare surface and air; find evidence of invisible water vapour.',
    },
    minutes: 18,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-condensation',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
  {
    id: 'phase-read-a-heating-curve',
    title: {
      zh: '加热曲线的平段，能量暂停了吗？',
      en: 'Does a flat heating curve mean energy input has paused?',
    },
    subtitle: {
      zh: '从−10℃冰到20℃水，把温度、状态与功率连起来。',
      en: 'Link temperature, state and power from −10°C ice to 20°C water.',
    },
    minutes: 20,
    stage: 2,
    unit: 'thermal',
    kind: 'phase-curve',
    pack: 'phase',
    predictionCount: 3,
    assessments: [
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 1,
      },
      {
        optionCount: 2,
        correct: 0,
      },
      {
        optionCount: 2,
        correct: 0,
      },
    ],
  },
];
